### ISSUE TITLE
browse and w3m

### ISSUE THREAD

**Issue by fatteneder** [xwmx/nb#106]
Hi,

I am having problems using the `browse edit` feature together with `w3m` and I hope someone here could help.

Steps to reproduce the problem:
1. `nb browse`
2. Navigate to a file.
3. Navigate to the `edit` button and hit enter.
4. Now I am in the edit mode but `w3m` does not allow me to make any persistent changes. If I issue my `EDIT` keybind I get the message `Can't edit other than local file`. If I issue the `EDIT-SCREEN` keybind then I can edit the stuff, but this is just a copy of the file and on saving (in my external editor) will not overwrite the file.

The same thing happens when running `nb browse add`.

Does anybody have an idea what the problem could be?
Or am I using the `browse` feature wrongly?

Versions:
- `w3m version w3m/0.5.3+git20210102`
- `nb 6.0.0-alpha`

Any help is very much appreciated.

**Comment by xwmx** [comment]
Hi @fatteneder, if you put the cursor in the textarea (defined by brackets, `[` `]`) and press <return>, the content should open in the editor, and then when the editor is closed the form textarea will have the new content and the save button should save it. Here's the w3m FAQ about forms: http://w3m.sourceforge.net/FAQ#www

According [the manual](http://w3m.sourceforge.net/MANUAL) it looks like the `E` keybinding is defined as "Edit buffer source", and when I try it I get the same "Can't edit other than local file", so it looks like that is for editing the source HTML of the page when a page is a locally-served HTML file, like an editable "view source."

I hope this helps!

**Comment by fatteneder** [comment]
Hi @xwmx,

thank you very much for your reply. This certainly clarifies a few things.

Pressing `<return>` within the bracketed text does work as you described and essentially solves my problem.

PS:
Before opening this issue I did read the `w3m` documentation you mention. 
However, for some reason I never considered treating the actual text inside the `[ ]` as a `form input field` and just using `<return>` to write into it. Instead, I even checked different terminal browsers and if they allow to modify the text through an external editor (as is mentioned in `nb`s documentation). Apparently, none worked.

> According the manual it looks like the E keybinding is defined as "Edit buffer source", and when I try it I get the same "Can't edit other than local file" message, so it looks like that is for editing the source HTML of the page when a page is a locally-served HTML file, like an editable "view source."

This then explains why I could edit local files without problems using the keybinds `E` and `ESC-E`.

**Comment by Sohail-XD** [comment]
I'm having a problem here. When I press enter inside the [ ] field, i get taken to kitty with a message [HIT ANY BUTTON] but when i do it takes me back to w3m window. Please help

**Comment by andd1e** [comment]
@Sohail-XD, had the same issue, configuring `editor nvim` in ~/.w3m/config (change nvim to your preferred editor) fixed it for me, for some reason w3m didn't listen to $EDITOR envvar
and if you want to specify filetype (e.g. markdown), change `editor nvim` to `editor nvim -c "set filetype=markdown"`, see full list of filetypes by `:setfiletype<space><C-D>` in nvim

https://w3m.rocks/config/#editor
