### ISSUE TITLE
Setting to create file from nb add before it is opened in the editor

### ISSUE THREAD

**Issue by enobrev** [xwmx/nb#11]
I'm trying to use `typora` as my editor and it seems `nb` expects the editor to create the file(?).  In typora I'm seeing 

![Screenshot-20201007133700-606x190](https://user-images.githubusercontent.com/584126/95373162-31e8da00-08a2-11eb-9f8a-a43d10d8f147.png)

> ENOENT: no such file or directory, open '/home/enobrev/.nb/home/-20201007183312.md'

I'm looking through `typora`'s preferences and seeing no option to have it create files if they don't already exist.  And so it seems something of an impasse.  Neither `typora` nor `nb` wants to create the file.  If there were some way to `touch` the file before opening it, whether in the `set editor` option or as another option, that would be most excellent.

**Comment by xwmx** [comment]
Interesting, and thanks for the heads up! I'll have to test with Typora and figure out which editors expect an existing file.

I also noticed that there's a hyphen at the beginning of the filename. What platform is this on?

**Comment by enobrev** [comment]
@xwmx  Ubuntu 20.04

I also found the dash strange and wondered if it might have been simply due to the fact that it injected a newline to fit the dialog.

**Comment by xwmx** [comment]
There is now a check for when `$EDITOR` or `nb set editor` is set to `typora` that creates the file before it opens in Typora.

This change is available as of 5.7.0.

Please let me know if you run into additional issues with this. Thanks!

**Comment by enobrev** [comment]
Confirmed.  Works great.  Thanks!

**Comment by xingheng** [comment]
Wierd, I get the [above changes](https://github.com/xwmx/nb/commit/c56aff28ee63013449c612a73391f8b7d26c115f) in version 5.7.8, but it reports 

```
/usr/local/bin/nb: line 1243: typora: command not found
```

I've defined the typora in my profile `alias typora="open -a typora"` and launch successfully in command line, does `nb` use standalone environment context?

**Comment by xingheng** [comment]
Confirmed, alias in bash profile is unaccessible in nb, but executable file in environment paths does, forwarding the alias to `/usr/local/bin/typora` works!

```
#!/usr/bin/env bash
open -a typora $@
```

**Comment by kdkasad** [comment]
> Confirmed, alias in bash profile is unaccessible in nb, but executable file in environment paths does, forwarding the alias to `/usr/local/bin/typora` works!
> 
> ```
> #!/usr/bin/env bash
> open -a typora $@
> ```

What if you try launching typora using the following command (without the `typora` script):
```sh
bash -c "typora"
```
I'd expect that it will report that `typora` is not found.

Usually, when commands run from within other programs do not respect your aliases, it's not actually the program's fault, but instead it's because bash does not expand aliases in commands provided using the `-c` option. I assume `nb` launches commands using `$SHELL -c "<command>"`, which causes bash to ignore the aliases.

However, this is an entirely separate issue from #11, so it probably shouldn't be discussed here.

**Comment by xwmx** [comment]
Indeed, aliases in the environment are not accessible within scripts by default. From the [Bash Reference Manual](https://www.gnu.org/software/bash/manual/html_node/Aliases.html):

> Aliases are not expanded when the shell is not interactive, unless the expand_aliases shell option is set using shopt (see [The Shopt Builtin)](https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html).

The editor can be set to Typora on macOS with:

```bash
nb set editor "open -a Typora"
```
