### ISSUE TITLE
'nb import' fails when passing notebook selector.

### ISSUE THREAD

**Issue by ohyhyb** [xwmx/nb#111]
Hey @xwmx,

I noticed in commit 09b5e90 you added some examples for 'import', however when passing a notebook selector it fails in a strange way. I've attempted to track down the issue but I can't figure it out myself.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/60670030/113854302-a390da80-9796-11eb-8b94-a6e35942983a.png">
When importing with `nb example:import example.txt` it works as expected though.

Regards

**Comment by xwmx** [comment]
OK. Thanks for letting me know. It should be working in the latest version.

**Comment by ohyhyb** [comment]
No problem, and yea it is working perfectly now.

I'll close the issue now as it is resolved, keep up the amazing work!
