### ISSUE TITLE
Rename Filename to Note Title

### ISSUE THREAD

**Issue by yumiris** [xwmx/nb#113]
This might end up being a pretty esoteric feature, but in essence: a feature where a note can be renamed to its current title. 

The foundation is already there, since `nb` can already:
- normalise given titles when using `nb add --title "Sweet Stuff"`; and
- parse titles from notes when using `nb ls` and numerous other commands.

It would be delightful to retroactively use a current title as the filename. The command could perhaps be something along the lines of:
```sh
nb rename 20210418081632.md --to-title
```
## Example
```
$ nb add -c "# A Rather Nifty Title"
# Added: [2] 20210513133436.org
```
```sh
$ nb rename 2 --to-title
# Moving:   [2] 20210513133436.org
# To:       a_rather_nifty_title.org
# Proceed?  [y/N] y
# Moved to: [2] a_rather_nifty_title.org
```

**Comment by xwmx** [comment]
@yumiris Thanks for thinking this through; I wanted it, too. This is now available as described along with various other improvements to `rename` / `move` in version 6.3.0. Let me know if you run into any issues with it.
