### ISSUE TITLE
Zettelkasten note-naming

### ISSUE THREAD

**Issue by gour** [xwmx/nb#116]
Hello,

I'm about to seriously start using `nb` for Zettelkasten and wonder how to easily achieve automatic naming of new notes according to common recommendation to use something like `yyyymmddhhss.md` for new notes and not to be bothered with manual naming?

**Comment by xwmx** [comment]
@gour That's actually the default behavior. `nb` uses `yyyymmddhhmmss` (specifically `date "+%Y%m%d%H%M%S"`) as the filename when no filename or only an extension is specified. For example:

```bash
❯ nb add "Example content."
Added: [1] 20210530123047.md

❯ nb add "Example content." .org
Added: [2] 20210530123115.org

❯ nb add "Example content." example-filename.org
Added: [3] example-filename.org
```

Let me know if this answers your question!

**Comment by gour** [comment]
> @gour Glad you like it. That's actually the default behavior. `nb` uses `yyyymmddhhmmss` (specifically `date "+%Y%m%d%H%M%S"`) as the filename when no filename or only an extension is specified. 

Ahh, that's perfect! How strange that I missed it... :blush: 

> Let me know if this answers your question!

Thanks a lot and please excuse me for the noise. :disappointed:

**Comment by xwmx** [comment]
Awesome. Let me know if you run into anything else.
