### ISSUE TITLE
A pinned folder stays pinned after removal

### ISSUE THREAD

**Issue by StanSvec** [xwmx/nb#117]
I had a sub-folder called `trip` in a folder called `todo`. The folder `trip` was pinned before. Then I deleted the folder `trip`:

❯ nb delete todo/trip
Deleting: [todo/1] 📂 todo/trip
Proceed?  [y/N] y
Deleted:  [todo/1] 📂 todo/trip

However the folder `trip` stays pinned and it cannot be unpinned (at least I don't know how):
![todopinned](https://user-images.githubusercontent.com/2771595/120930743-1ad2e400-c6de-11eb-8d7c-288739b5819b.png)

**Comment by xwmx** [comment]
@StanSvec Thanks for the heads up! I’m still working on this. In the meantime, you should be able to remove the entry manually using: `nb edit todo/.pindex`

**Comment by StanSvec** [comment]
Nice, that worked. Thanks for showing me this solution. :)

**Comment by xwmx** [comment]
@StanSvec Awesome. I made a couple updates to avoid this happening again, available as of version 6.3.4. Thanks again!
