### ISSUE TITLE
basic task management?

### ISSUE THREAD

**Issue by rhaynes74** [xwmx/nb#119]
Hi folks, I hope things are well.   Has there been any effort to incorporate task management features with nb? Maybe through taskwarrior? 

Best,
R Haynes

**Comment by xwmx** [comment]
@rhaynes74 Indeed. There is a nascent (and currently not enabled) `todo` / `todos` subcommand [in the code](https://github.com/xwmx/nb/blob/264852b326f00e34eba6f7b7be0d88df85f594b6/nb#L20955) that so far just lists open and closed todos from markdown files.

**Comment by xwmx** [comment]
`nb` 6.7.0 includes [Todos](https://github.com/xwmx/nb#-todos) and [Tasks](https://github.com/xwmx/nb#--tasks).

**Comment by rhaynes74** [comment]
Many thanks for letting me know!

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
