### ISSUE TITLE
Any option to add a bookmark offline?

### ISSUE THREAD

**Issue by chmac** [xwmx/nb#130]
I misunderstood the `--skip-content` option, I assumed it meant that the URL being added like `nb url --skip-content` would not be fetched, but would just be added directly to the markdown file. I realise that the description section is fetched from the URL, and so a network request is actually made.

I'm working on a script to import large numbers of bookmarks, so I was hoping to skip all network operations as I already have all the data that I want to include. Is there any way to do that currently? I couldn't find anything in the docs, but maybe there's an OFFLINE environment variable or some other magic option? :-)

**Comment by chmac** [comment]
In the meantime, thanks to #5, I was able to script the creation of the files very easily. I replicated the `.bookmark.md` format and then added the filenames to `.index`. These two lines, followed by the `git add . && git commit ...` work like a charm:

https://github.com/chmac/scuttle2nb/blob/2c97769dde64cfcbd786ed1487ce2c0398e0d7a5/src/index.ts#L141-L142

**Comment by chmac** [comment]
Ah, just found the `--no-request` flag. EPIC! Thanks a lot @xwmx. Can I close this issue now? Seems like it's very much there.

**Comment by xwmx** [comment]
@chmac Indeed! Thanks for the reminder.
