### ISSUE TITLE
add support for asciidoc

### ISSUE THREAD

**Issue by wuzhe** [xwmx/nb#132]
Please add support for asciidoc document format.

**Comment by amithm7** [comment]
I think support has to come from `pandoc`. https://github.com/jgm/pandoc/issues/1456

**Comment by xwmx** [comment]
As of `nb` version 7.2.0, [AsciiDoc](https://asciidoc.org/) is now supported when [Asciidoctor](https://asciidoctor.org/) is available on the system. Let me know if you run into any issues with it.

**Comment by wuzhe** [comment]
awesome, thank you.
