### ISSUE TITLE
tput: command not found

### ISSUE THREAD

**Issue by BuzzwordChief** [xwmx/nb#133]
Due to the missing mobile client I tried to install nb on iSH (Linux shell for iOS). Even with satisfied dependencies I get this error: 
`sh 
iPhone-von-David:/usr/local/bin# nb
/usr/local/bin/nb: line 759: tput: command not found`

GNU bash, version 5.0.17(1)-release (i586-alpine-linux-musl)

git version 2.26.3

**Comment by xwmx** [comment]
@BuzzwordChief Thanks for the heads up. It looks like it’s in the `ncurses` package. I just set it up in iSH (which is pretty cool) and I think I got it running with `apk add bash git ncurses`

**Comment by BuzzwordChief** [comment]
Yeah works when installing ncurses
