### ISSUE TITLE
Extra characters when piping `nb show` to pbcopy

### ISSUE THREAD

**Issue by joshtemple** [xwmx/nb#142]
I was hoping to run `nb show [ID] -p | pbcopy` on MacOS to get my note in clipboard so I could paste it into Slack. When pasting, I got a ton of unwanted character codes.

For example:
```
[37m---[0m
[37mtitle: Consult with Joe Weber[0m
[37mpeople: Joe Weber[0m
[34m---[0m
```

Instead of:
```
---
title: Consult with Joe Weber
people: Joe Weber
---
```

**Comment by xwmx** [comment]
Indeed, those are the color escape sequences for the syntax highlighting, which can be disabled with the `--no-color` option, e.g., `nb show [ID] -p --no-color | pbcopy`. `nb` defaults to using color for most output and `--no-color` works globally with all commands to print output without the escape sequences for use cases like this.

**Comment by joshtemple** [comment]
Perfect, that fixes it. Thank you!
