### ISSUE TITLE
How to get notebook given filename

### ISSUE THREAD

**Issue by joshtemple** [xwmx/nb#144]
I'm working on a post-commit script to parse my notes and sync certain lines to Todoist as tasks.

I'd like the project name of the Todoist task to match the notebook name. To do this, I need to be able to get the name of the notebook given only the note's filename.

Is this possible?

**Comment by xwmx** [comment]
The notebook name can't be determined by just the filename using `nb` directly. Is the post-commit script within a notebook repository? The notebook name is the repository folder name.

**Comment by joshtemple** [comment]
It is, which is what I ended up using. With zsh, the following works for me:

```
${$(nb --paths --no-id $FILENAME):h:t}
```

**Comment by xwmx** [comment]
Awesome!
