### ISSUE TITLE
nb browse broken on termux

### ISSUE THREAD

**Issue by paperbenni** [xwmx/nb#145]
![photo_2021-09-19_16-57-19](https://user-images.githubusercontent.com/15818888/133932253-aaac9a41-30fa-4ef8-b08b-80aa8faa0584.jpg)

Picture says it all, running nb browse and nb browse -g on termux inserts all these markers into the html. 
This is tested on the newest termux version from f droid, nb from master and readability-cli and pandoc installed

**Comment by xwmx** [comment]
Thanks for the heads up. These markers are removed with `sed` calls: [[1]](https://github.com/xwmx/nb/blob/master/nb#L10274) [[2]](https://github.com/xwmx/nb/blob/master/nb#L10070). I'm looking for a way to run Termux to try to determine why they aren't working.

**Comment by xwmx** [comment]
I was able to run it via Android Studio. It looks like the issue mentioned in https://github.com/termux/termux-packages/issues/6429 is a factor. I replaced the unicode characters in the markers with just ASCII, and now `nb browse` renders output in Termux without the markers. I'll have to do more testing.

**Comment by xwmx** [comment]
This should be working now. I also eliminated the hard `tput` and `file` dependencies, which aren't installed by default on Termux. I'll leave this issue open until these changes are in a version release.

**Comment by paperbenni** [comment]
Works on my end, thanks a lot!
