### ISSUE TITLE
completions install fails to identify zsh on arch linux

### ISSUE THREAD

**Issue by meredrica** [xwmx/nb#150]
Hi
I'm using zsh 5.8 with OMZ on arch linux
running `sudo nb completions install --download` only installs the bash completions.
I found no way to force it to also download zsh completions.

**Comment by yumiris** [comment]
Exact same issue here (albeit with vanilla Zsh instead of OMZ). Works fine on Ubuntu; on Arch Linux, I had to:
```sh
sudo pacman -S zsh zsh-completions
sudo mkdir -p /usr/local/share/zsh/site-functions
sudo curl https://raw.githubusercontent.com/xwmx/nb/master/etc/nb-completion.zsh > /usr/local/share/zsh/site-functions/_nb
```

**Comment by meredrica** [comment]
Working as of 6.7.0 with my setup

**Comment by yumiris** [comment]
No dice on my end:
```sh
miris ~ % sudo rm -rvf /usr/share/bash-completion/completions/nb
miris ~ % sudo rm -rvf /usr/share/zsh/site-functions/_nb
```
```sh
miris ~ % nb --version
6.7.0
miris ~ % sudo nb completions install --download
Completion script installed: /usr/share/bash-completion/completions/nb
```

**Comment by meredrica** [comment]
@yumiris i moved away from omz, now completions are broken. looking for a fix right now

**Comment by meredrica** [comment]
hah. fixed it. 
steps:
- the completions file **must** start with `_`
- add the folder to `$fpath`
- enjoy
