### ISSUE TITLE
Tag listing doesn't work

### ISSUE THREAD

**Issue by fredrikekre** [xwmx/nb#154]
I can not get tag listing to work with any of the suggested commands in the documentation. Here is from a completely clean slate:

```
$ nb
-------------------------------
        Welcome to
        __          _
        \ \   _ __ | |__
         \ \ | '_ \| '_ \
         / / | | | | |_) |
        /_/  |_| |_|_.__/
-------------------------------
               home
-------------------------------
0 items.

[...]


$ nb add --tags foo,bar --title baz "foo bar baz" foo.md
Added: [1] foo.md "baz"

$ nb --tags
No #hashtags found.

$ nb ls --tags
No #hashtags found.

$ nb list --tags
No #hashtags found.

$ nb home/ --tags
No #hashtags found.

$ nb home:1 --tags
No #hashtags found.

$ nb 1 --tags
No #hashtags found.

$ nb foo.md --tags
No #hashtags found.
```

Searching for tags seem to work though, so they seem to be recognized as tags.
```
$ nb search --tag foo
[1] baz
-------
3:#foo #bar

$ nb search --tag bar
[1] baz
-------
3:#foo #bar
```

nb commit: faca241cea4631fbf923dea36a58c62e244ae436

**Comment by xwmx** [comment]
@fredrikekre Thanks for the heads up. I simplified the pattern and added your example as a test that’s now passing, so it should be working in the latest revisions. Let me know if it’s still not working.

**Comment by fredrikekre** [comment]
Thanks for the quick response, unfortunately I still have the same issue. I noticed the command uses grep, maybe I have an old version or something?

```
$ grep --version
grep (GNU grep) 2.25
```

**Comment by xwmx** [comment]
Interesting. It uses [`git grep`](https://git-scm.com/docs/git-grep) in particular. Is the system’s git version current?

**Comment by fredrikekre** [comment]
Ah okay, that seems to be the problem then:
```
$ grep --color=never --extended-regexp -I --ignore-case --only-matching -e '#[A-Za-z0-9_-]+' .nb/home/foo.md                                                                 
#foo
#bar

$ git grep --color=never --extended-regexp -I --ignore-case --only-matching -e '#[A-Za-z0-9_-]+' .nb/home/foo.md                                                             
error: unknown option `only-matching'
```

**Comment by xwmx** [comment]
@fredrikekre Good to know. It looks like the `—only-matching` option was added in version 2.19, which was a few years ago so I think it’s ok to leave it and not do a version check.

While looking into this I found a bug that prevented some tags from matching and the resolution is in the newest version, 6.7.5.

I’ll go ahead close this. Please let me know if you run into any new issues.

**Comment by fredrikekre** [comment]
Yea no worries. Does `nb` in general hide errors from sub commands like this? Personally I would have appreciated to see the error instead, then I would never had bothered you with this issue :)

**Comment by xwmx** [comment]
`nb` generally either produces its own output or processes the output of the underlying tool in some way. The search tools and operations are wrapped in pipelines and nb performs its own error checks after filtering results.

This is a unique case that came up due to a variety of contextual factors. I added a version check and a `find` + `grep` fallback, so it should work fine now regardless of the git version, just slightly slower on systems with git versions before 2.19.

I appreciate you creating the issue and bringing this to my attention. I wouldn't have easily known otherwise, and this feature is more robust now.

**Comment by fredrikekre** [comment]
Great, thanks for the fixes!
