### ISSUE TITLE
Any possibility to set bookmark filenames?

### ISSUE THREAD

**Issue by chmac** [xwmx/nb#158]
nb https://xwmx.github.io/nb/#nb-help
    Added: [19] 🔖 20211223151602.bookmark.md

Is there any option to somehow set the `20211223151602` part from the bookmark URL? I can imagine that it raises difficult questions around duplicates and so on.

I could also write some wrapping code to check the index, then try to calculate a bookmark link, and finally call `nb <url>`, but I can't see any option to set the filename in the docs. Does that exist? Maybe this would be an easier thing to add rather than logic about URL parsing, etc. I'd be delighted with an option like `nb <url> --filename foo` where the bookmark ends up called `foo.bookmark.md`.

Once again, thanks for `nb`, it's really epic to be able to manage all this stuff in plain files in a git repo. Here's to open data in this holiday season! :-)

**Comment by xwmx** [comment]
Glad you like it!

The `nb <url> --filename <filename>` / `-f <filename>` option is actually available. :-) `nb https://example.com/ --filename foo` should indeed produce a bookmark with the filename `foo.bookmark.md` as described. I just tried it locally and it worked. Let me know if it doesn't work on your system or needs tweaking.

**Comment by xwmx** [comment]
Also, FWIW, the documentation for the bookmarking options is on the [`bookmark` subcommand](https://github.com/xwmx/nb#bookmark), which `nb <url>` is internally a shortcut for. I'll review the help around this to see if it can be improved.

**Comment by chmac** [comment]
Apologies, I missed that in the docs, sorry about the spurious issue. I'll write some scripts to extract a suggested name, check it's uniqueness and then use the `--filename` flag.

I'm loving nb more and more. I become increasingly dedicated to storing my personal data of this nature in simple, plain text files which I can expect to still be able to read decades from now. 🧡
