### ISSUE TITLE
Error with 'code --new-window' as the EDITOR

### ISSUE THREAD

**Issue by mekanics** [xwmx/nb#16]
When I try to run `nb add` or `nb edit <id>` I get the following error 
```bash
$ nb add
/usr/local/bin/nb: line 1512: code --new-window: command not found
```

I have my `EDITOR` env variable set to `code --new-window`.  

nb version: 5.5.1 (installed with brew)

**Comment by xwmx** [comment]
This should now be resolved as of version 5.5.3. Please re-open if you encounter additional issues with this. Thanks!
