### ISSUE TITLE
some commands hang after exiting

### ISSUE THREAD

**Issue by ExpandingMan** [xwmx/nb#165]
If I, for example, do `nb e 6`, make some changes, exit the editor (`nvim` in my case) I am not returned to the prompt until typing `ctrl-c`.  Edits work properly, it's just a matter of getting stuck without a prompt.

Is happening on `fish`, `zsh` and `bash`.

**Comment by xwmx** [comment]
The main operation after editing a file is a git commit and sync operation [[1]](https://github.com/xwmx/nb/blob/4b9e77267d0bf673e2f930ff3f113d8add64fc4e/nb#L13262) [[2]](https://github.com/xwmx/nb/blob/4b9e77267d0bf673e2f930ff3f113d8add64fc4e/nb#L3246). Perhaps there is something about the git configuration that's causing an unhandled error. What is the OS and `git --version`? Do you have notebooks configured to sync with remotes?

**Comment by ExpandingMan** [comment]
Ah, sorry, this was mostly my fault!

For one, I thought I had auto-sync disabled, but I realized that it wasn't set in my `.nbrc`, so I forgot that it even had to do with the sync.  It does seem that the sync was hanging and I'm not really sure why, especially since `nb sync` works just fine.  Since I didn't want it to auto-sync in the first place, disabling it solves the problem for me (it doesn't seem to be hanging).

Thanks!

**Comment by ansonyuenr2c2** [comment]
A different but relevant problem:

I have nb syncs to `gitlab.com` and `AUTO_SYNC` turned on. It hangs quite a while (3 - 10 seconds) whenever I save a note though. It impedes my flow as I often want to open another note to immediately write down other ideas for the same project.

Is there a recommended setup where I can exit editing a note and start a new one immediately?
