### ISSUE TITLE
[Feature Request] Allow diferent URL schemes

### ISSUE THREAD

**Issue by dluciv** [xwmx/nb#167]
[Right now, only few URL schemes are supported](https://github.com/xwmx/nb/blob/d2d97a5b41f321e51ab65bfa8b322e37810d380f/nb#L3005), despite of many existing schemes and protocols. Many of [those](https://en.wikipedia.org/wiki/List_of_URI_schemes) are useful.

I suggest adding a variable to `.nbrc` with a list of user-defined schemes and add them to default ones.

**Comment by xwmx** [comment]
@dluciv Thanks for the heads up. This should automatically support most URLs and schemes now, the only notable exception being those that would conflict with notebook selectors. This is available as of version 6.9.3. Let me know if you run into any issues with it.

**Comment by dluciv** [comment]
@xwmx Not all schemes work, e.g. [gemini://](https://en.wikipedia.org/wiki/Gemini_(protocol)) causes «! No URL found.» message.

**Comment by xwmx** [comment]
@dluciv A full URL like `gemini://example.com/` should work. I added a test for it. Any alphanumeric scheme in a URL with that format should match the [first pattern here](https://github.com/xwmx/nb/blob/bd6a1cd838bd89ef27acf0fd859d827f0541255b/nb#L3072). Does `gemini://example.com/` work on your end?

**Comment by dluciv** [comment]
@xwmx Nope...

`nb bk gemini://example.com/` stores a bookmark file, but `nb open` claims `! No URL found.` `gemini://gemini.dluciv.name/` also fails.

At the same time, Gopher works correctly `nb bk gopher://gopher.dluciv.name/`.

Checked with `nb` 6.11.2 in OS X and Linux. Having no `.nbrc`.
