### ISSUE TITLE
existing backup file from emacs ~ broke nb list & more

### ISSUE THREAD

**Issue by doolin** [xwmx/nb#173]
Here was the state which resulted in `nb` returning 1 (`$ echo $?` => 1)

File exists: `home/book-reviews/the-road-not-taken.org~`

`.index` contained `the-road-not-taken.org~`

`*~` is in `.gitignore`, 

From the bash prompt, `nb` was a no-op returning 1. I "fixed" it by removing the file from the filesystem and the filename from the index.

**Comment by xwmx** [comment]
Hi @doolin! It sounds like this is the same as #171. I just published a new version, 6.9.4, that should skip common temp files. Please try upgrading and let me know if the issue is resolved.

**Comment by doolin** [comment]
Duplicate!
