### ISSUE TITLE
Showing pdfs with termpdf

### ISSUE THREAD

**Issue by maxdiebold-erg** [xwmx/nb#177]
I use the **kitty** terminal, and I have **termpdf** installed, but `nb show` is still opening pdfs with `less`. Am I missing some configuration?

**Comment by xwmx** [comment]
Hi @maxdiebold-erg! There are two versions of `termpdf`, and currently only [termpdf.py](https://github.com/dsanson/termpdf.py) is supported, so make sure that's the version installed. If it's still not working, you can try opening the file directly in termpdf.py with `termpdf.py /path/to/example/file.pdf`.

**Comment by maxdiebold-erg** [comment]
Ah that solved it! Thanks!
