### ISSUE TITLE
Search results don't make sense

### ISSUE THREAD

**Issue by joshtemple** [xwmx/nb#178]
Hi! Thank you for this wonderful software, I use it every day to take notes and it's become invaluable to me (not to mention it's helping me get much better with vim).

I'm having a hard time with `nb search` and I'm not sure what I'm doing wrong.

For example, simple searches like `nb search "a"` or `nb search "the"` don't return any results. I have hundreds of notes, so that doesn't make sense to me, even if I think about it as a regex.

If I change the search to `nb search "the a"`, then I get results like, "We want to add **the a**bility", so there are clearly results there, I'm just not understanding why these single-word searches don't work. What am I doing wrong?

**Comment by joshtemple** [comment]
I should've done this first, but I've upgraded nb with `brew upgrade nb`, and this seems to be resolved! I will close this issue.

**Comment by xwmx** [comment]
@joshtemple Happy to hear it’s working now. 😃
