### ISSUE TITLE
[Question] any specific reason why an import cannot be tagged?

### ISSUE THREAD

**Issue by adulau** [xwmx/nb#183]
First of all, thanks for nb. It's really nice!

[Question] any specific reason why an import cannot be tagged? I'm trying to import all my pinboard.in links into a specific notebook but I'm loosing the metadata such as tag or description.

**Comment by xwmx** [comment]
Hi @adulau, glad you like it!

Currently the `import` subcommand only does copy, move, and download operations. There is no bookmark import functionality yet. This kind of import could be performed with a script or plugin that parses the exported bookmark file and then creates `nb` bookmarks for each one.

**Comment by adulau** [comment]
Thanks for the clarification. I’ll have a look at the plugin approach.

**Comment by xwmx** [comment]
@adulau This piqued my interest, so I added experimental Chrome bookmark importing with `nb import bookmarks <path>`. It uses the timestamp for the filename and bookmark title for `nb` bookmark title. I can try adding Pinboard support at some point if there's an example export file I could work from.

**Comment by xwmx** [comment]
I added support for Firefox bookmarks, which use the same file format as Chrome, and now it also includes tags.

**Comment by PresGas** [comment]
This looks exciting, @xwmx !! I have a couple of questions. 

I am looking at the code and seeing the guts of the import of bookmarks, but not sure where I can see the actual command to call the function (it is a lotta lines!! :grinning: ). Are we supposed to export the initial bookmarks and then use that file to import into `nb`? 

Another thing I noticed (at least for firefox) is that you can "backup" bookmarks as a `json` file. Do you think that would be easier to parse and import over the exported html file?

**Comment by xwmx** [comment]
@PresGas Bookmarks are created within [`_import_create_bookmark()` (line 14685)](https://github.com/xwmx/nb/blob/23b0bb430b02956db70538ad61f879f0b3ebfea5/nb#L14685), which calls the `_bookmark()` function at the end. The bookmark file parsing is on [line 14921](https://github.com/xwmx/nb/blob/23b0bb430b02956db70538ad61f879f0b3ebfea5/nb#L14921).

I just added an example `json` backup to `text/fixtures`. Everything is on one line, but a new dependency like `jq` could be used to parse it.
