### ISSUE TITLE
Issue with using ssh-keys in git

### ISSUE THREAD

**Issue by dj-bauer** [xwmx/nb#19]
I have an ssh-key for my git repo, but this messes up the syncing process after editing, so I had to disable auto syncing
What I have to do is to manually do `nb sync` and then type my key passphrase twice, until it syncs successfully.

Anybody else having this issue?

**Comment by dj-bauer** [comment]
I could fix it by using using ssh-agent so far, which is a good habit anyways I guess.

**Comment by xwmx** [comment]
Thanks for the information! I'm looking into ironing this out.

**Comment by xwmx** [comment]
The prompts, documentation, error handling, and test coverage around this have been greatly improved, so this issue should be resolved. Prompts for credentials should now be fully suppressed during automatic syncing. Credentials have to be cached for auto sync, and the [README](https://github.com/xwmx/nb#private-repositories-and-git-credentials) and [`sync` help](https://github.com/xwmx/nb#sync) now contain information about caching git credentials.

These changes are available as of version 5.7.0.

Thanks for the heads up! Please let me know if you encounter continued issues with this.
