### ISSUE TITLE
Bat dependency check for debian should be updated

### ISSUE THREAD

**Issue by tkapias** [xwmx/nb#191]
Currently, in Debian, `nb env install` check for the command 'batcat' or try to install bat 0.16.0 (let's say too that I didn't like that it is trying to downgrade forcefully to 0.16.0 without reason, 'bat' was marked on hold on my system because of that).

But, the issue at the root of the executable renaming on Debian was [resolved](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932634) recently.

I use Debian SID/Testing, 'bat' version is 0.21.0-2 and for at least 1 month there is no more 'batcat' executable. The package at the source of the conflict, libyaml, is not present anymore.

Then you should probably check for bat and then batcat with `_command_exists` in the nb executable.

I opened a [bugreport](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019734) upstream because they should have mentioned something in the changelog at least.

**Comment by xwmx** [comment]
Thanks for the heads up! I added a check for both executable names and updated the fallback package version. These changes are in the version in the repository and will be in the next release.
