### ISSUE TITLE
nb todo add opens help when text contains 'check'

### ISSUE THREAD

**Issue by meredrica** [xwmx/nb#194]
Seems like some command parser fails here.
When you run ``nb todo add 'check this out'`` it will open the help for todos.
Running ``nb todo add 'try this out'`` works as expected.

nb version 6.11.2

**Comment by xwmx** [comment]
@meredrica thanks for the heads up! This should be resolved in recent versions. Please let me know if you run into additional issues with it.

**Comment by meredrica** [comment]
no, works perfectly since your push
