### ISSUE TITLE
[Feature Request] allow to clean up todos

### ISSUE THREAD

**Issue by meredrica** [xwmx/nb#197]
By now, my todo list (especially the done part) is getting out of hand in nb.

Is there a way that I missed to clean them up? I'd like to archive them all at once, move them to a folder or even delte them. I guess I could write a simple script but I think a command like `nb todos clean` would be nice.

**Comment by richardsc** [comment]
I second this suggestion! Especially since I don't currently see a way to archive notes/todos, only notebooks.

Thanks for the great tool! I've been slowly working it into my daily workflow.

**Comment by borjarobert** [comment]
In case it's useful to you, I made a half-baked plugin called `tclean`that does that. I have a `done/` folder in every notebook. When I finish for the day, I run `nb tclean` which checks all the closed todos (not recursively) and moves them to `done/`.


Here is my code in case it helps. I'm no bash connoisseur, so please try it on a backup notebook first. No guarantees!

```bash
#!/usr/bin/env bash
###############################################################################
# tclean.nb-plugin
#
# Moves all done items to folder done/ in active notebook
#
###############################################################################

# Add the new subcommand name with `_subcommands add <name>`.
_subcommands add "tclean"

# Define help and usage text with `_subcommands describe <subcommand> <usage>`.
_subcommands describe "tclean" <<HEREDOC
Usage:
  nb tclean

Description:
        Just moves done todos to the folder 'done/'
HEREDOC

# Define the subcommand as a function, named with a leading underscore.
_tclean() {
        # get all ids of items you want to move to done folder
        _notebook_current="$(nb notebooks current)"
        nb_closed_items="$(nb run "$_notebook_current":todos closed --no-color | awk '{print $1}' | cut -d\[ -f2 | cut -d\] -f1)"
        
        for i in $nb_closed_items; do
                nb run "$_notebook_current":move "$i" done/ -f
        done
}
```

**Comment by meredrica** [comment]
Thanks for the scrip but I've long since moved on to obsidian. It doesn't have a cli, which is a tragedy, y but it handles most things a lot better.
