### ISSUE TITLE
Commands slow since adding git-sync. Can syncing be done in the background?

### ISSUE THREAD

**Issue by trekze** [xwmx/nb#199]
I'm on wsl2. I use nb with git-sync and vscode (when running nb edit).

I find the 4-5 second delay annoying that you get between closing vscode and nb returning to the shell.

Is there any way around this?

**Comment by PresGas** [comment]
You can turn off auto-sync, which is on by default.
https://xwmx.github.io/nb/#auto_sync
Just know you will then have to make sure and do an `nb sync` when you feel done. Add the `--all` flag if you have multiple notebooks.
