### ISSUE TITLE
grep warnings on various nb commands

### ISSUE THREAD

**Issue by jkaiser-ioki** [xwmx/nb#202]
Hi,

I am just getting started with `nb` but I noticed various grep warnings:

```
grep: warning: stray \ before @
grep: warning: stray \ before !
grep: warning: stray \ before /
```

sometimes that block of warnings pops up multiple times. So far I noticed it on calls to `nb a` and `nb notebooks add`, but so far I cannot see a pattern on when this happens.

Can anyone tell me what is going wrong here and how to potentially fix this.

In case that it matters ... I am on an Arch linux system, fully updated.

**Comment by xwmx** [comment]
This should be resolved now as of version 7+. Thanks!
