### ISSUE TITLE
How to change color in view/show mode

### ISSUE THREAD

**Issue by vkuznet** [xwmx/nb#21]
Hi, I got very light color in view/show mode. Regardless how I change the theme it always stays the same (light grey). I do have bat installed but bat shows my markdown in totally different color (almost black). My question where/how to change view/show color.

**Comment by xwmx** [comment]
Hi! The syntax theme can be configured with the `nb set syntax_theme` subcommand. Are you able to update the syntax theme using `nb set syntax_theme`? Also, running the command `bat --list-themes` should display a list of themes with highlighted examples, so if that looks OK, then `bat` is working.

**Comment by vkuznet** [comment]
Great, that's exactly what I was looking for, it worked, closing the ticket.
