### ISSUE TITLE
Install failed via brew. Conflict on bash-completion.

### ISSUE THREAD

**Issue by adoyle-h** [xwmx/nb#210]
<img width="829" alt="CleanShot 2022-10-25 at 15 50 00@2x" src="https://user-images.githubusercontent.com/1998490/197715032-89056517-0ccf-45cd-a04e-8095c6da2a1b.png">

I'm using bash-completion@2. But `nb` dependent on bash-completion@1. Can you fix the brew package to be compatible with bash-completion@2?

**Comment by xwmx** [comment]
@adoyle-h Done. Thanks for the heads up!
