### ISSUE TITLE
URL_PATTERNS regex not matching some git url's

### ISSUE THREAD

**Issue by ohyhyb** [xwmx/nb#215]
Hey @xwmx,

Now that `_string_is_url` is being called with `_init_create_home_notebook()` the regex fails to validate git url's in the format of `git@host.com:user/repo.git` i've stumbled upon a regexp which works:

`([A-Za-z0-9]+@|http(|s)://)|(http(|s)://[A-Za-z0-9]+@))([A-Za-z0-9.]+(:d+)?)(::|/)([\d\/\w.-]+?)(\.git)`

but rather than open a pull request I'll let you decide how best to address this one ;)

Regards

**Comment by xwmx** [comment]
@ohyhyb Thanks! I added a pattern for this and it's available in version 7.1.1.
