### ISSUE TITLE
[Consistency bug] prefix of 'slash'

### ISSUE THREAD

**Issue by adulau** [xwmx/nb#220]
I was wondering if this is a consistency bug or by design.

If you have a folder `daily`, `nb list` is not showing the content of the folder if you do

- `nb list /daily/`
but if you do 
- `nb list daily/` you get the list inside the folder.

**Comment by xwmx** [comment]
Hi @adulau! Thanks for reaching out. This is actually intended behavior. A leading slash (`/`) makes `nb` treat a selector as an absolute file / folder path. See examples here: https://github.com/xwmx/nb#examples I omitted absolute paths in the `Usage` sections to keep them simpler, so absolute path support is a slightly hidden feature.

Let me know if you have any additional thoughts or comments. I'll think about ways to better document this behavior.
