### ISSUE TITLE
Zsh suppot

### ISSUE THREAD

**Issue by ss-o** [xwmx/nb#221]
I have made the `nb` zsh-plugin with the binaries and completions that can be managed by most zsh-plugin managers and after a few minor changes can be made standalone and proposed to [OhMyZsh](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins) repository or etc.

Let me know what you think :dart: 

- https://github.com/z-shell/nb

<div align="center">

![nb](https://user-images.githubusercontent.com/59910950/208319179-2a508a42-1bf0-46c7-ad57-e26587aa16de.gif)

![nb](https://user-images.githubusercontent.com/59910950/208319198-f2c03e58-91be-4880-a53f-894f3f6257c2.png)

</div>

**Comment by anoduck** [comment]
My God! It is beautiful.

**Comment by xwmx** [comment]
@ss-o Thanks for doing this! I haven't had a chance to check it out yet, but hope to soon.

**Comment by ss-o** [comment]
This is just an example and does not support a standalone install or have any Zsh features. It is a simple repository structure that allows using binaries `bookmark`, `nb`, `notes`, `completions`, or any other library in the repo using almost any zsh-plugin-manager. The rest depends on how you would like/want to extend with Zsh. Check it out and ping me when/if you have any ideas/questions and we then can make further adjustments. :+1: 

> P.S. I currently use all nb features in zsh with my plugin manager with almost no problems (unable to use commands/functions which require/use sudo access), and would like to extend nb with Zsh features where/if possible.
