### ISSUE TITLE
nb ls --tags or nb q --tags only shows the first tag on each line

### ISSUE THREAD

**Issue by ejheil** [xwmx/nb#224]
From the docs, "nb ls --tags" and "nb q --tags" are supposed to show the tags in the current notebook, however they only seem to find the first tag on a given line in a note.

```
➜  ~ nb add --tags foo,bar "This is tagged with foo and bar"
Added: [1] 20221223163610.md
➜  ~ nb show --print 1
#foo #bar

This is tagged with foo and bar
➜  ~ nb ls --tags
#foo
➜  ~ nb search --tags
#foo
➜  ~
```

It would be helpful to either fix this or make a note of it in the documentation.

**Comment by xwmx** [comment]
Apparently the latest version of `git` changed the way it handles patterns in `git grep` and `\s` needed to be replaced with `[[:space:]]`. This should be working now as of version 7.2.1. Let me know if you run into additional issues with it. Thanks!

**Comment by ejheil** [comment]
Awesome, thanks!
