### ISSUE TITLE
[User Tip] Not seeing icons in nb (ls) listing? A possible solution...

### ISSUE THREAD

**Issue by ArchieLinux** [xwmx/nb#226]
Just a tidbit I stumbled across in not being able to see the icons in an nb listing, in case it's helpful to others in the future...

Turns out, since nb is command line (bash) based, if you're not seeing those little icons next to certain entries in your nb listing, it may simply be that you don't have your bash environment settings ready to display "emojis" in a console font.

That was the case in my minimal Arch/wmi3 tiling environment: I did not have anything like the "Noto Color Emoji" font installed - no less enabled within my bash "konsole." 

Once I did, those nb icons show up as intended. This is not an nb issue, it's a bash/konsole environment issue. HTH.

**Comment by xwmx** [comment]
@ArchieLinux Thanks for the information!

**Comment by TheTaoOfPhil** [comment]
This solved my problem running nb in kitty. I just had to remember to exit all kitty sessions and restart it :-)
Many thanks!
