### ISSUE TITLE
nb sync ... fails, keeps asking for github credentials, but why?

### ISSUE THREAD

**Issue by ArchieLinux** [xwmx/nb#227]
Context: I've successfully installed & sync'ed **nb** with my two private github repos (zettlekasten-style markdown file collections) on 2 separate Arch/EndeavourOS/wmi3 platform setups here at home using https protocol. Awesome.

But...

Having repeatedly followed all the same steps on our 3rd such PC (identically configured), I can't get past the `nb sync` command line without **nb** repeatedly asking for my github credentials. 

Using **gh** I've successfully installed and confirmed my token credential as evidenced here:

```
[me@Dell-i3 ~]$ gh auth status
github.com
  ✓ Logged in to github.com as ArchieLinux (oauth_token)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
```
... so I it seems unlikely it's a github thing (and again, the other 2 nb installs work perfectly with the same two repos). 

I've uninstalled and wiped clean any .nb related files and reinstalled (twice) but continue to be asked for my github login credentials by **nb** whenever trying to sync with my github repos, ultimately getting a failure message each time:

```
[me@Dell-i3 ~]$ nb sync
Syncing: XXXXX ...Username for 'https://github.com': ArchieLinux
Password for 'https://ArchieLinux@github.com': xxxxxxxx
Username for 'https://github.com': ArchieLinux
Password for 'https://ArchieLinux@github.com': xxxxxxxx
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/ArchieLinux/xxxxxx/'

```
(Note the "xxxxx" above are just for privacy, not the actual entries ;-)

The notice about password authentication being removed in Aug 2021 is what led me to install and authorize tokens using **gh** (girthub CLI) - which is what I also had to do to get the other 2 setups working. It doesn't seem to be doing the trick in this 3rd case.

What's more, nb seems to be telling me that the remote connection has been made...
```

[me@Dell-i3 ~]$ nb remote status
https://github.com/ArchieLinux/xxxxx (master)
```

Anyone have thoughts as to what else I might try to get this last PC connected with **nb** & **github**? Thoroughly love using nb on the other two machines... 3rd time should be a charmer :-)

**Comment by xwmx** [comment]
@ArchieLinux Glad you are enjoying `nb`! `nb` mostly uses the `git fetch` command here, so you can try running that and other git operations in a notebook directly (or even with `nb git`, e.g., `nb git fetch origin`) to better identify the issue.

It sounds like there is something happening with the `gh auth login` credential caching. I recommend checking [the GitHub documentation](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git) and making sure it works with normal git commands.

**Comment by ArchieLinux** [comment]
@xwmx Thanks for your suggestion and patience. I eventually made time to go back and try again (would've been more urgent if I didn't have things working properly on two other platforms) ... and after torturing myself with github (`gh`-CLI) efforts I got things cloned and operating within `nb` just fine. User error, as usual.
