### ISSUE TITLE
Improve display of PDF files

### ISSUE THREAD

**Issue by kovidgoyal** [xwmx/nb#23]
Currently nb uses pdftotext, which is suboptimal for PDF files contain anything other than simple text. Consider using https://github.com/dsanson/termpdf.py which displays rendered PDF in the terminal instead. Note that it works only in the kitty terminal currently.

**Comment by xwmx** [comment]
Great idea. Thanks for the tip! As of version 5.6.0, when using kitty with termpdf.py available in the environment, `nb` uses that to display pdfs automatically. For other terminals it continues falling back to `pdf2text` if available, or the system pdf viewer if not.

Let me know if you run into additional issues with this.

**Comment by kovidgoyal** [comment]
you are most welcome
