### ISSUE TITLE
nb browse does not work with GUI browsers

### ISSUE THREAD

**Issue by OGKevin** [xwmx/nb#230]
On a fresh installation on Ubuntu and MacOS, `nb b` opens `w3m`, which works fine.
But when u ask `w3m` to open the page in an external browser by hitting `M`, or by running `nb b -g` or `nb -s`, it does not work.
Visiting the page in Firefox, Safari, Chrome, lynx, or qutebrowser they either fail to render the page or show "corrupted" HTML.

<img width="1624" alt="Screenshot 2023-01-14 at 08 37 27" src="https://user-images.githubusercontent.com/17928966/212461649-49af2c07-27cc-4846-bc87-5a1a1f46927b.png">
<img width="1512" alt="Screenshot 2023-01-14 at 08 38 33" src="https://user-images.githubusercontent.com/17928966/212461691-63168a71-2174-4b0c-9a6c-ced70e679d74.png">

Is `nb` using `http 0.9`? Or is there something wrong with my installation? I doubt this due to doing it even on a clean linux vm.

What could the issue be here? 
I'm happy to provide missing info.

**Comment by OGKevin** [comment]
After a lot of fiddling around, I can conclude that this is due to not having the git repo setup. Even having it in a dirty state causes this 😕

**Comment by xwmx** [comment]
@OGKevin Thanks for the information. It looks like the server process is somehow printing the spinner or something else with the response. I haven't reproduced the issue in my environment yet to determine the cause. When the repo is dirty on my system and I run `nb b -s`, the spinner is displayed in the terminal and then the server starts normally.

If you can identify a series of commands that reproduce the configuration and the issue, that could help me reproduce it.

I pushed an update that limits when the git checkpoint spinner is displayed. I don't know if it will help here. It's available in the latest revision in the repository if you want to try.

**Comment by OGKevin** [comment]
I think this happens when `git commit` fails for whatever reason. 
e.g. not having git author setup. Or signing the commit fails.
