### ISSUE TITLE
Error: `sed: -e` no such file or directory

### ISSUE THREAD

**Issue by anoduck** [xwmx/nb#231]
`nb` was installed and working fine, until it was updated to the newest release. Then it started to spit out this error and no longer works. OpenBSD and other UNIX* do not user GNU's sed, they use the original sed. This limitation is usally overcame by the incorporation of an alias in the shell rc file. That alias is present in my shell, but regardless, nb is not picking up on the alias and continues to output this error.

**Comment by anoduck** [comment]
Well apparently, much to my unfailing chagrin and completely unknown to myself, my alias for sed is missing in my `zshrc`  file. :man_facepalming: 

Regardless, `nb` is back online and working smooth as silk. Such an excellent program.

Thanks!

**Comment by xwmx** [comment]
Glad it works!

**Comment by anoduck** [comment]
@xwmx I am so embarrassed.

**Comment by xwmx** [comment]
@anoduck Don't be at all. There are so many moving parts, and this issue led to improved compatibility with different versions of `sed`. Thanks! 😄
