### ISSUE TITLE
Add NOT operator to search 

### ISSUE THREAD

**Issue by d-a-chapman** [xwmx/nb#247]
Loving nb -- thanks. 

Is it possible to run a search query that returns files that don't match the query? I want to show notes that don't have a certain tag. I've tried using `q \#tag --invert-grep`, as per git grep documentation, but this doesn't work. Am I not doing something right or is this a missing feature? 

Thanks!

**Comment by xwmx** [comment]
@d-a-chapman Glad you like it!

Thanks for the suggestion. I went ahead and added support for `--not` in `search` in the latest version in the repository. I still have to document the option before including it in a release version. Let me know if you run into any issues with it.

**Comment by xwmx** [comment]
This is available and documented as of version 7.5.0. @d-a-chapman Thanks for bringing this up.
