### ISSUE TITLE
Hello, nb how to change the ID number

### ISSUE THREAD

**Issue by shuen2023** [xwmx/nb#251]
NB is a great project. Thanks 😊. But I was confused that when I deleted a record, the ID number of that record was gone. I want to know how to change the ID number? I want that ID number.

**Comment by elementum74** [comment]
Index is handled via `.index` file in the nb directory e.g. `~/.nb/home`.  Change the sequential order to change the id.

**Comment by shuen2023** [comment]
> 

thank you!

**Comment by shuen2023** [comment]
> 索引是通过`.index`nb 目录中的文件处理的，例如`~/.nb/home`. 更改顺序以更改 id。

i like you😇
