### ISSUE TITLE
Page content in bookmarks gets not cleaned up

### ISSUE THREAD

**Issue by 1837456** [xwmx/nb#252]
Hello,

first I have to say thank you! A few days ago I discovered nb and it's just awesome and fits perfectly in my more and more text based workflows.

There is only one thing not working for me: I'm on macOS Mojave (10.14.6), using Kitty with Bash (5.2) and have installed both, pandoc and readability-cli to clean up the markup of my bookmarks. But that does not happen. Maybe it's something that only works on Linux?

I have almost everything installed via Homebrew, except node/npm for readability-cli. The pandoc command is available but not the readable one.

Thanks in advance for any tip.

Alex

**Comment by 1837456** [comment]
I'm sorry, the path was not set correctly. Working now. And again: happy to have found nb.

**Comment by xwmx** [comment]
@1837456 Glad you figured it out, and happy to hear you like `nb`! 😊
