### ISSUE TITLE
Cheque ésto?

### ISSUE THREAD

**Issue by cttemux** [xwmx/nb#26]
eyJ1c2VyX2lkIjoiMTc1MGRiZGMtYTEyZC02YTZlLWE2YmEtY2FlMTgyZTRiMDc4IiwiY3JlYXRlZCI6IjIwMjAtMTAtMDlUMTQ6MjI6MjMuNjUwWiIsInVwZGF0ZWQiOiIyMDIwLTEwLTA5VDE0OjIyOjIzLjY1MFoiLCJ2ZXJzaW9uIjpudWxsfQ==

**Comment by cttemux** [comment]
Encriptación de datos de llamada revisa

**Comment by IggySaban** [comment]
> eyJ1c2VyX2lkIjoiMTc1MGRiZGMtYTEyZC02YTZlLWE2YmEtY2FlMTgyZTRiMDc4IiwiY3JlYXRlZCI6IjIwMjAtMTAtMDlUMTQ6MjI6MjMuNjUwWiIsInVwZGF0ZWQiOiIyMDIwLTEwLTA5VDE0OjIyOjIzLjY1MFoiLCJ2ZXJzaW9uIjpudWxsfQq==
> 

`dirk `
