### ISSUE TITLE
Error with fish completion

### ISSUE THREAD

**Issue by the-solipsist** [xwmx/nb#263]
I'm using fish-shell version 3.6.1 with nb version 7.5.5.

If I type `nb [tab]`, I get this error:

```
sol@spica ~> nb test: Missing argument at index 3
 !=
    ^
/tmp/nb-completion.G6c4af (line 17): 
      or test "$_notebooks_cached" != (string join " " $_notebooks)
         ^
in function '_cache_completions' with arguments '-e /tmp/nb-completion.G6c4af /home/sol/.nb/.cache/nb-completion-cache-v2'
	called on line 48 of file /tmp/nb-completion.G6c4af
nb open 3    nb test: Missing argument at index 3
```

This seems to relate to this line:
https://github.com/xwmx/nb/blob/master/etc/nb-completion.fish#L45

But I'm not sure what the problem is. Is anyone else facing anything similar?

**Comment by zicklag** [comment]
I get a weird `rm: remove regular file '/tmp/nb-completion.aqzA7p'?` message every time it spits out an autocompletion when I install it with `fish 3.1` and `nb 7.5.5`.

**Comment by xwmx** [comment]
Thanks for the information. It looks like there's an issue with the temp file handling. What OS are you encountering this on? Completions seem to be working for me on macOS Ventura 13.4 with Fish 3.6.1 and `nb` 7.5.5.

**Comment by zicklag** [comment]
I'm on Pop!_OS ( Ubuntu ) 20.04. It may have something to do with an alias or something somewhere that makes rm ask for confirmation when removing. Maybe it just needs a `-f` flag to force removal or something?

**Comment by the-solipsist** [comment]
I'm on Endeavour OS.
```
uname -a
Linux spica 6.4.7-arch1-3 #1 SMP PREEMPT_DYNAMIC Wed, 02 Aug 2023 09:47:27 +0000 x86_64 GNU/Linux
```

I don't seem to have this problem with any other fish tab completion, only with nb.

**Comment by xwmx** [comment]
I tried in Ubuntu 22.10 [via Vagrant](https://github.com/xwmx/nb/blob/master/etc/Vagrantfile) and `fish` completions worked as expected. I added an EndeavorOS box to try and haven't been able to get it to provision completely. I'll keep trying to reproduce the issue.

**Comment by xwmx** [comment]
I also tried in Arch and completions worked as expected. I still couldn't get EndeavorOS to provision completely. If anyone knows how I can easily reproduce the issue on Ubuntu or Arch, let me know.

**Comment by zicklag** [comment]
Thanks for trying! Since that worked fine, I'm assuming it's something specific to my environment.

**Comment by the-solipsist** [comment]
Update: I moved all the (non-hidden) folders from `~/.nb` and the problem resolved itself.  I don't know why this worked, but it did. I then moved all the folders back, and the completions are still working.

For now, I think I can close this issue. If this problem re-occurs in a reproducible manner, I think it can be re-opened.
