### ISSUE TITLE
in-code `rm` may cause irritating verbose output when tab completion is used

### ISSUE THREAD

**Issue by susca** [xwmx/nb#268]
Problem: When the user has `alias rm="rm -v"` or similar in their bash config, every time the tab is pressed for completion, an output occurs that a cache file has bee removed, which is very annoying and obfuscates the command. The same issue is probably also present for fish, zsh, etc.

Proposed solution: instead of `rm` use `\rm` wherever applicable in the code.

**Comment by xwmx** [comment]
I replaced `rm` with `\rm` in the `.zsh` and `.bash` completion scripts. It looks like the fish completion issues aren't directly related to this. The following command should reinstall the completion scripts using the latest version from the repository:

```bash
nb completions uninstall && nb completions install --download
```

@susca Please let me know if you run into any additional issues with this. Thanks!
