### ISSUE TITLE
Directory Tools updates for exa/eza, lsd & joshuto

### ISSUE THREAD

**Issue by tkapias** [xwmx/nb#271]
- **exa is now [deprecated](https://github.com/ogham/exa#exa-is-unmaintained-use-the-fork-eza-instead)**.
- [eza](https://github.com/eza-community/eza) is the maintained and active fork of exa.
- [lsd](https://github.com/lsd-rs/lsd) released v1.0.0 and is mature and has nicer features than exa/eza (better scale-coloration, yaml config and stability).
- [Joshuto](https://github.com/kamiyaa/joshuto) does not take the `--path` argument anymore.

I suggest to:

- Remove **exa** from the list in a few month.
- Add **eza** in a higher priority than exa.
  - Here is a nice command line for eza: `eza -1labm --icons --sort=name --color=always --color-scale --group-directories-first --git --git-ignore --no-user --time-style=long-iso`
- Add **lsd** in a higher priority than eza.
  - lsd can be setup with a config file but for nb I have this nice command line: `lsd --ignore-config -1Al --date '+%F %R'  --color=always --icon=always --icon-theme=fancy --size=short --group-directories-first --blocks=permission,size,date,git,name --git`
- Remove `---path` from the nb command line for joshuto (`joshuto --path "${_target_path}"`).

**Comment by xwmx** [comment]
@tkapias Thank you for the detailed information. This was extremely helpful. I included the changes as described and they are available in the latest version, 7.6.0.
