### ISSUE TITLE
Errors running `nb browse` and `nb edit` commands

### ISSUE THREAD

**Issue by davidmickelsen** [xwmx/nb#273]
I've just installed nb and I've added one bookmark. However, I'm getting errors when trying to run a couple of commands.

When I run `nb browse 1`, I get the error message: 

`w3m: Can't load http://localhost:6789/home:1?--limit=68&--terminal&--columns=92.`

and when I run `nb edit 1`, I get the error message:

`/usr/local/bin/nb: line 10121: code: command not found`

I had previously run `nb set editor code` to (attempt to) set the editor to VS Code, which returned `EDITOR set to code`.

Admittedly (not that it's not obvious), I'm a little inexperienced using the command line.

**Comment by xwmx** [comment]
@davidmickelsen Thanks for the information. What method did you use to install `nb` and what is the operating system?

**Comment by davidmickelsen** [comment]
Thanks for your reply. I installed nb using `brew install nb`; I'm running macOS Monterey 12.6.8.

**Comment by xwmx** [comment]
@davidmickelsen Thank you.

I don't immediately know why `nb browse 1` isn't working. The error indicates that the server isn't starting for some reason even though `ncat` is available via the `nmap` package that's automatically installed with `nb`. I'll have to figure out how to reproduce the error. You could try adding the `--print` option to the command to see whether it produces any output or errors: `nb show 1 --print`

The error with `nb edit` indicates that the VS Code command line tool, `code`, is not available in the environment. It might need to be installed via the VS Code command palette as described in the following documentation: https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

Let me know if this helps!

**Comment by davidmickelsen** [comment]
Thanks for your reply, @xwmx.

`nb show 1 --print` worked to display the content of the site in the terminal, with no errors.

After installing the VS Code command line tool via the instructions at the link you sent, I ran `nb edit 1` and the markdown file opened in VS Code.

Success all around!

**Comment by xwmx** [comment]
@davidmickelsen Good to hear. Is `nb browse` working yet? If not, you could also try running `brew reinstall nmap` and then try `nb `browse` again.

**Comment by davidmickelsen** [comment]
Hi @xwmx, I ran `nb browse 1` again, and it is now working. Thanks again for your help.

**Comment by xwmx** [comment]
@davidmickelsen Awesome. Great to hear. Thanks!
