### ISSUE TITLE
[Feature Request] Custom option for pandoc when using nb browse

### ISSUE THREAD

**Issue by EarthMessenger** [xwmx/nb#275]
I want to use customize pandoc option (for example `east_asian_line_breaks`) when using `nb browse`. However there isn't such setting. I hope nb can add a setting for this.

**Comment by xwmx** [comment]
@EarthMessenger I've included `east_asian_line_breaks` by default in `browse` now. I'll try to look at making the `pandoc` options from customizable in `browse`.

**Comment by xwmx** [comment]
The Markdown reader and extensions for `nb browse` can now be customized using the [`$NB_BROWSE_MARKDOWN_READER`](https://github.com/xwmx/nb#nb_browse_markdown_reader) variable. This extension is already enabled via the default value: `markdown+emoji+raw_html+east_asian_line_breaks`. Let me know if you run into any issues with it!
