### ISSUE TITLE
nb url - strip out navigation before converting to markdown

### ISSUE THREAD

**Issue by jgm** [xwmx/nb#29]
I just tried `nb url` on this repository and I got a markdown file with lots of navigation links.  Would it be possible (perhaps as an option) to pipe the HTML through something like [readability-cli](https://www.npmjs.com/package/readability-cli) before converting to markdown?  That would remove a lot of extraneous clutter.

**Comment by xwmx** [comment]
Great idea. Thanks! As of the latest version, 5.5.9, readability-cli's `readable` is used automatically if it's found in the environment. I experimented with it and it seems to work very well.

Thanks for checking it out. I've been a big fan of Pandoc for a long time!
