### ISSUE TITLE
"! Web browser not found. Try `w3m`: http://w3m.sourceforge.net"

### ISSUE THREAD

**Issue by voxelv** [xwmx/nb#297]
Whenever I try `nb browse`, I get the error:
> ! Web browser not found. Try `w3m`: http://w3m.sourceforge.net

I've tried for a few hours to install w3m on Windows without success.
Compared to the other recommended dependencies, w3m seems to be much less Windows-friendly.

I read about browse Portability at https://github.com/xwmx/nb#browse-portability, but for me it seems I can't use `nb browse` without w3m.

Am I doing something wrong? Are there other options available?

**Comment by xwmx** [comment]
I don't currently have a Windows system to test on, so I'm going by memory. My understanding is that `w3m` doesn't work on WSL 1 (see #9), but `lynx` might work in that environment, and that `w3m` should work in WSL 2. I think you should be able to install `w3m` in WSL 2 with `sudo apt install w3m` (maybe after running `sudo apt update`). You should be able to confirm whether it's installed by running `which w3m`. The browser can also be set to `w3m` by adding the following line to `~/.nbrc`: `export NB_BROWSER="w3m"`. Let me know if any of this helps!

**Comment by voxelv** [comment]
Thanks for responding! 

I'm not using WSL, but I found that w3m is available via MSYS2, and it works by itself there. When I try `nb browse` again, it doesn't work (there's just a blank page). This seems to be a different issue, so I'll open a new issue.

**Comment by voxelv** [comment]
My solution was to install `w3m` via MSYS2.
