### ISSUE TITLE
Support lowercase #+title: for Org-mode files

### ISSUE THREAD

**Issue by jackbaty** [xwmx/nb#305]
If possible, it would be nice if nb could recognize lowercase `#+title:` front matter in org-mode (.org) files.

A lowercase `#+title:` in .org files is not recognized by nb as the document's title. Using up-cased `#+TITLE:` works fine. Recent versions of Org support (and encourage (based on [this mailing list post](https://list.orgmode.org/87tuuw3n15.fsf@nicolasgoaziou.fr/)) the use of lowercase in front matter.

Thanks for nb!

**Comment by xwmx** [comment]
@jackbaty Thanks for the heads up. This should be working with lowercase as of version 7.12.1.
