### ISSUE TITLE
Allow adding flags to $EDITOR

### ISSUE THREAD

**Issue by fsmiamoto** [xwmx/nb#32]
This is a **feature request**.

I would like to be able to add flags to my editor, using `nb set editor`

In my case , I wanted to use `nvim` with `Goyo` so I've done the following: 
```sh
$ nb set editor
...
Enter a new value, unset to set to the default value, or q to quit.
Value: nvim -c Goyo
EDITOR set to nvim -c Goyo
```

But trying to open a new note yields the following:
```sh
$ nb add
/home/shigueo/.local/bin//nb: 行 1512: nvim -c Goyo: Command not found
```

I'm not an Bash expert but this could probably be something not to difficult to support.

Thanks for the awesome tool!

**Comment by xwmx** [comment]
This should be fixed in the latest versions. I've been pushing new updates with bug fixes, so check `nb --version` and if it reports earlier than 5.5.7, upgrade, try again, and please let me know if it works then.

**Comment by fsmiamoto** [comment]
@xwmx 
Thanks for the quick response!
My bad on that one, should've pointed out my version which was `5.5.1`.
Updating to `5.5.7` fixes the problem :+1:

**Comment by xwmx** [comment]
Awesome!
