### ISSUE TITLE
German symbols for "nb ls --tags" not supported

### ISSUE THREAD

**Issue by commonist** [xwmx/nb#329]
Dear devs,
thanks for this nice peace of software. Would you mind to add German symbols ä, ö, ü, and ß to the regex for listing the tags. This is not supported (yet). German tags like "Föderation" are not handled correctly. 

The same counts for file name matching. 

Thanks a lot in advance.

**Comment by xwmx** [comment]
@commonist Thanks for the heads up. This should be resolved as if version 7.14.0 and higher. Please let me know if you run into any more issues with it. Thanks!
