### ISSUE TITLE
Add Uninstallation Instructions

### ISSUE THREAD

**Issue by stwhite** [xwmx/nb#33]
What are the steps to uninstall nb?

I delete /usr/local/bin/nb and ~/.nb, is that sufficient?

**Comment by dmiraj** [comment]
This may not be the way you were looking for but if you cloned the repo into your user directory:
Simply run:
`make uninstall`
This command will remove nb from your system. You can then run:
`sudo apt autoremove` to remove all unused dependencies that were previously used by the program.

**Comment by stwhite** [comment]
Thanks
