### ISSUE TITLE
When NB_GUI_BROWSER is set,  the open command doesn't work

### ISSUE THREAD

**Issue by ericguirbal** [xwmx/nb#336]
On my Debian box, I can open a bookmark in a web browser as long as the environment variable `NB_GUI_BROWSER` is not set. If `NB_GUI_BROWSER` ∈ {"firefox", "dillo"}, `nb open` open `file://home/eric`. If `NB_GUI_BROWSER`  ∈ {"chromium",  "brave-browser", "luakit"}, `nb open`  launches the browser with a *blank page* (no url).

**Comment by xwmx** [comment]
@ericguirbal Thanks for the heads up. There was a bug in the code that should be resolved as of version 7.14.0 and higher. Please let me know if you run into any more issues with it. Thanks!
