### ISSUE TITLE
Removing todos

### ISSUE THREAD

**Issue by Draiken** [xwmx/nb#339]
I've noticed there is no "delete" command for todos. Is there a design decision around that or it could be implemented?

Thanks for the awesome tool!

**Comment by xwmx** [comment]
@Draiken Glad you like it! The [`nb delete`](https://xwmx.github.io/nb/#delete) subcommand also deletes todo items. I also just added a [`nb todo delete`](https://xwmx.github.io/nb/#todo) subcommand as you expected. This is available in version 7.14.0 and above. Let me know if you run into any issues with it. Thanks!
