### ISSUE TITLE
nb doesn't check "alternatives" in /etc/alternatives/editor

### ISSUE THREAD

**Issue by jwrightecs** [xwmx/nb#340]
On systems using alternatives from `/etc/alternatives` (ubuntu, others), nb ignores `/etc/alternatives/editor` instead trying $EDITOR $VISUAL then the hard coded list in nb.sh (which usually ends up with nano, whose sole positive attribute is that it isn't pico.

adding `editor` as the first entry in `_editors`, or even as the first entry before `nano` would be an improvement

**Comment by xwmx** [comment]
@jwrightecs I added `editor` as requested and this is now available in version 7.14.6. Please let me know if you encounter any issues with it. Thank you!
