### ISSUE TITLE
'delete' or 'todo delete' using title fails or will try to delete the whole notebook

### ISSUE THREAD

**Issue by tkapias** [xwmx/nb#342]
The help for `delete` and `todo delete`, like many other commands, indicate that you can provide the item by id, filename or title.

But currently, trying to use the title, with a notebook specified, will try to delete the whole notebook:

```
nb todo delete notebook:folder/"my todo"

Deleting notebook.

This action cannot be undone. This will permanently delete the
notebook notebook, all notes and files it contains,
and the entire revision history.

Please type home to confirm:
```

Without the notebook name, it just fails:

```
nb todo delete folder/"my todo"
! Not found: folder/my todo
```

With a flename or ID, it works.

**Comment by xwmx** [comment]
@tkapias Thank you for letting me know. This should be resolved as of version 7.14.3. Please let me know if you run into any additional issues with it.
