### ISSUE TITLE
Wrong help is shown when arguments are missing from 'rename' invocation

### ISSUE THREAD

**Issue by xstasi** [xwmx/nb#343]
Hello there! `nb` is showing the help for `show` instead of the right command when calling `rename` or one of its aliases.

Steps to reproduce:

1. Type any of
* `nb mv`
* `nb move`
* `nb rename`
2. Help for `nb show` appears
3. Type `nb help mv`
4. Correct help appears

**Comment by xwmx** [comment]
@xstasi Thank you for letting me know. This should be resolved as of version 7.14.4. Please let me know if you run into any more issues with it. Thanks!
