### ISSUE TITLE
`less` version check errors when the version string is a point release

### ISSUE THREAD

**Issue by sahensley** [xwmx/nb#344]
The version of `less` on macOS Sonoma 14.7 is 581.2.  

When `nb` does the `less` version check seen [HERE](https://github.com/xwmx/nb/blob/master/nb#L2534), the following error is thrown to the console: `line 2534: [[: 581.2: syntax error: invalid arithmetic operator (error token is ".2")`

This has not impacted functionality as far as I can tell, just the error is raised on the console.

**Comment by xwmx** [comment]
@sahensley Thanks for letting me know. This should be resolved as of version 7.14.5. Please let me know if you run into any more issues with it.
