### ISSUE TITLE
Tags for notes?

### ISSUE THREAD

**Issue by daturkel** [xwmx/nb#37]
Hi, thanks for the amazing tool! 

I'm wondering if tags are supported for notes, or only for bookmarks? I would love to be able to tag notes but can't seem to figure out how. Thanks!

**Comment by xwmx** [comment]
Thanks! It's actually really easy in this application: just add hashtags anywhere in a document. You can then search for them as hashtags using `nb search "#example-tag"` or `nb q "#example-tag"`. The idea is that your documents stay tagged using a standard plain-text tagging format, searchable and extractable by `nb` and any other program, now or in the future.

The bookmark `-t` / `--tag` option is provided as a convenience saving a bookmark and takes save the specified tags as hashtags within the `## Tags` section of the bookmark file. There isn't the same workflow for notes, so the `-t` / `--tags` option is only available when saving a bookmark.

I added some documentation about this in the README.

I hope this helps. Let me know if you have any additional questions or comments about this, and thanks for checking out `nb`!

**Comment by daturkel** [comment]
This is perfect, thanks for the explanation!
