### ISSUE TITLE
Encryption silently fails when no gpg/openssl available

### ISSUE THREAD

**Issue by kedorlaomer** [xwmx/nb#39]
I tested on a fresh alpine container after installing `apk add bash git vim bat pandoc ack tig w3m ripgrep ncurses`:

        nb add --encrypted "Shouldn't fail"

The status code is 127 and nothing is saved anywhere. I would expect an error message explaining what went wrong (couldn't execute gpg nor openssl). Even better: Store the note in some scratch space (e. g., don't delete the temp file) and warn the user it wasn't saved.

**Comment by xwmx** [comment]
Thanks for the information! I updated `nb` so it exits with an error if the `-e` / `--encrypt` option is used when the encryption tool is not available. Let me know if you encounter more issues with this, or if there's a problem with this solution.
