### ISSUE TITLE
LC_ALL cannot be set on Arch Linux and causes nb to fail

### ISSUE THREAD

**Issue by d3vr** [xwmx/nb#4]
LC_ALL cannot be set on Arch Linux ([link to wiki](https://wiki.archlinux.org/index.php/Locale#LC_ALL:_troubleshooting)), so the only way I found to use nb is to prefix the nb command with `LC_ALL=en_US.UTF-8 nb` which isn't really practical. I'm guessing the strict mode at the top of the script is what's causing it to exit with an error when LC_ALL is unset (`set -o nounset`).

What fix do you suggest in this case?

EDIT: For now I've temporarily commented out the `set -o nounset` line at the beginning of the script.

Thank you.

**Comment by xwmx** [comment]
Hi @d3vr! Thanks for the heads up. I just pushed a fix for this that is available in version 4.1.25. Please let me know if you run into any more issues with this. Thanks!

**Comment by d3vr** [comment]
Lovely, thank you for the quick fix!
