### ISSUE TITLE
Does edit with vscode work?  With "code" set as $EDITOR, nb home:1 edit does nothing

### ISSUE THREAD

**Issue by alanwunsche** [xwmx/nb#44]
"nb home:1 edit" seems to do nothing.  Should it open VS Code?

**Comment by xwmx** [comment]
Yes, `nb home:1 edit` should open the specified note in VS Code when `$EDITOR` is set to `code`. I don't know why it wouldn't open. I just tested on macOS and it works as expected for me. What platform are you on? Is there any output? You can also try setting the editor for `nb` specifically with `nb set editor code` and then see if that makes a difference. Another thing to try would be setting it to `vim` or another editor and make sure that works.

**Comment by alanwunsche** [comment]
Catalina recently notified me of the following and this was completed:
- - - - -
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
- - - - -
 
When I `nb set editor code` , zsh terminal returns  `EDITOR set to code`
But `nb home:1 edit` just returns to terminal with seeming no action.
Running Version: 1.50.0
- - - - -

`nb set editor vim` returns `EDITOR set to vim`
Vim opens with :
E325: ATTENTION
Found a swap file by the name "~/.nb/home/.20201012230716.md.swp" and other error code.  It suggests deleting the swap file.
I deleted the swap file and vim worked fine

**Comment by alanwunsche** [comment]
I also noticed that it was trying to open VSCodium.app in the try but never succeeded.  
I deleted VSCodium.app and then tried `nb home:1 edit`. 
Response:
`/usr/local/bin/nb: line 1621: code: command not found`

**Comment by xwmx** [comment]
Looks like the `code` executable isn't available in the environment. You might need to install the `code` command line tool using the instructions here:

```text
You can also run VS Code from the terminal by typing 'code' after adding it to the path:

- Launch VS Code.
- Open the Command Palette (⇧⌘P) and type 'shell command' to find the Shell Command: Install 'code' command in PATH command.
- Restart the terminal for the new $PATH value to take effect. You'll be able to type 'code .' in any folder to start editing files in that folder.
```

https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

Does it work after performing those steps?

**Comment by alanwunsche** [comment]
Thanks, that solved the problem!

**Comment by xwmx** [comment]
Awesome!
