### ISSUE TITLE
Feature Request: import all files in a directory

### ISSUE THREAD

**Issue by andrewhoplife** [xwmx/nb#49]
At present nb import works on single file names only. While using a for loop does the trick with:

```for file in * ; do nb import $file ; done ```

```nb import *``` 

is more concise and a logical enhancement.

**Comment by xwmx** [comment]
Agreed! I've updated `nb import` to support globbing and multiple path arguments, and also added new tests covering this. This also makes it possible to do things like `nb import *.md`. This change is available on master and will also be available in the next release.

Thank you for bringing this up!

**Comment by xwmx** [comment]
This is now available as of version 5.7.1
