### ISSUE TITLE
Documentation of the format in use?

### ISSUE THREAD

**Issue by chmac** [xwmx/nb#5]
Firstly, I love the look of nb, thanks for releasing this. ❤️ 

I'm building a few things in the browser with git as a backing store. One of my hot targets is bookmarking. I wonder if it would make sense to use the same format as nb? Is the format you use documented somewhere that would make it easy to copy?

I'm really inspired by the ecosystem that built up around [todo.txt](http://todotxt.org). I'm hoping we can start to see a suite of apps which use very standard, very simple formats to store data in git repos. Then we could switch between different front ends, terminal, mobile, web, etc, and always share the same underlying data storage. That's the big dream anyway! :-)

**Comment by xwmx** [comment]
Thanks for the kind words. Awesome ideas! Sounds like we are on a similar frequency.

I did an initial pass at this and added details about the bookmark file format and notebook specification to the bottom of the README:

- https://github.com/xwmx/nb#nb-markdown-bookmark-file-format
- https://github.com/xwmx/nb#nb-notebook-specification

Let me know if that covers everything!

**Comment by chmac** [comment]
@xwmx Awesome, that looks great.

How does the encryption work? Is it only the contents of the file which are encrypted? Is the user required to supply the key / passphrase on each invocation?

I'm wondering if I could build a web based frontend, or maybe a mobile app, that would support the same format. The spec of your index file is interesting. Especially the option to delete a file but preserve the newline. Smart way to generate IDs. Have you seen any issues with merges?

I have built a task manager based on markdown storing the data in git. Inspired by the [todo.txt](http://todotxt.org) format, but extended for markdown. I think I probably went a bit overboard and added a little more complexity than was required, but anyway... I have the recurring issue that if 2 inserts happen at the same point (most commonly the start of the file) then it throws a git merge error. I wonder how that would work with the index file and the line numbers...

**Comment by xwmx** [comment]
> How does the encryption work? Is it only the contents of the file which are encrypted? Is the user required to supply the key / passphrase on each invocation?

Each note is encrypted individually and the user is always prompted for the password. `add`, `edit`, `show`, `bookmark`, `open`, and `peek` also accept an undocumented `--password <password>` option that circumvents the prompt and is currently used in the tests, and that option can be used for passing the password in scripts / code.

> The spec of your index file is interesting. Especially the option to delete a file but preserve the newline. Smart way to generate IDs. Have you seen any issues with merges? ... I have the recurring issue that if 2 inserts happen at the same point (most commonly the start of the file) then it throws a git merge error.

Thanks for the heads up. After seeing your question last week I experimented with `nb` and was able to reproduce this issue with `.index` in `nb` when two clones of a notebook create new files and then sync. To resolve thse conflicts, `nb` now checks if `.index` is the only conflicted file during a rebase error and, if so, keeps both changes and continues the rebase ([nb#L935](https://github.com/xwmx/nb/blob/master/nb#L935)). There is also a new [sync test](https://github.com/xwmx/nb/blob/master/test/sync.bats) covering this case.

Other merge conflicts still require manual resolution (which the `nb git` subcommand makes more convenient) and if `.index` is conflicted with other files then it would require manual resolution along with the other conflicted files.

**Comment by xwmx** [comment]
Actually, I realized that I could just implement conflict resolution logic so users don't have to resolve conflicts with `git`, so that is now available as of version 4.7.4. See the [Sync Conflict Resolution](https://github.com/xwmx/nb#sync-conflict-resolution) section of the README for more info.

**Comment by chmac** [comment]
I'll close this now as I think the docs are excellent. Thanks for adding that. 👍
