### ISSUE TITLE
too slow `nb ls -a`

### ISSUE THREAD

**Issue by delphinus** [xwmx/nb#50]
I have over 2000 notes in a notebook. It is so annoying `nb ls -a` takes huge seconds.

```
time nb ls > /dev/null

________________________________________________________
Executed in  892.78 millis    fish           external
   usr time  369.04 millis    0.14 millis  368.90 millis
   sys time  538.45 millis    2.35 millis  536.10 millis

time nb ls -a > /dev/null

________________________________________________________
Executed in   63.53 secs   fish           external
   usr time   29.17 secs    0.14 millis   29.17 secs
   sys time   33.19 secs    1.97 millis   33.19 secs
```

Over 1 minute! Can I shorten this?

**Comment by xwmx** [comment]
How are you trying to use it? For scripting / coding, such as writing a plugin, `ls` and `list` can be called with options to avoid extra file system operations, and the `run` subcommand can be used to run shell commands directly. For example, here is a demonstration of the time difference on a similarly-sized notebook (`list` is the same as `ls` but without the header, footer, and limit):

```bash
> nb count
2497
> time nb list > /dev/null
nb list > /dev/null  20.58s user 12.79s system 94% cpu 35.485 total
> time nb list --no-id --no-indicators --filenames > /dev/null
nb list --no-id --no-indicators --filenames > /dev/null  0.46s user 0.17s system 104% cpu 0.608 total
> time nb run ls >/dev/null
nb run ls > /dev/null  0.15s user 0.13s system 97% cpu 0.284 total
```

Note that it looks like it took twice as long on your device as it does on mine, so the device performance appears to be a factor.

By default, `ls` and `list` iterate over each file, read the beginning looking for titles and first lines, and also retrieve the id for the filename from the index. Each operation increases the amount of time it takes to display the line. This default behavior of `ls` / `list` is designed for human use and consumption, while still providing options to remove the display elements of each list item when they aren't needed and when performance matters at lot, such as in code.

So far, performance optimizations for the default, human-oriented `ls` and `list` behavior have been focused on getting as much out of standard unix tools as possible before relying on caching or new optional dependencies (there is some initial caching being used for completions). 

Does this answer your question?

**Comment by delphinus** [comment]
I want list up notes with titles to filter them by user input: ex. `nb list | fzf`.

Hmm... Perhaps, UNIX commands are too slow in macOS? Or, I have notes with a lot of CJK characters and commands such as `sed` has weak spots for them?

<details><summary>various <code>nb list</code> on my box</summary>

```sh
> nb count
2813

> nb list > /dev/null

________________________________________________________
Executed in   72.27 secs   fish           external
   usr time   30.62 secs  123.00 micros   30.62 secs
   sys time   41.88 secs  858.00 micros   41.88 secs

> nb list --no-id > /dev/null

________________________________________________________
Executed in   18.91 secs   fish           external
   usr time   10.91 secs  131.00 micros   10.91 secs
   sys time    8.43 secs  964.00 micros    8.43 secs

> nb list --no-id --filenames > /dev/null

_______________________________________________________
Executed in    3.74 secs   fish           external
   usr time    3.51 secs  147.00 micros    3.51 secs
   sys time    0.27 secs  1032.00 micros    0.27 secs

> nb list --no-id --filenames --no-indicator > /dev/null

________________________________________________________
Executed in  654.73 millis    fish           external
   usr time  450.35 millis  142.00 micros  450.21 millis
   sys time  232.45 millis  1165.00 micros  231.29 millis

> nb run ls > /dev/null

________________________________________________________
Executed in  255.68 millis    fish           external
   usr time  114.14 millis  139.00 micros  114.00 millis
   sys time  131.52 millis  969.00 micros  130.55 millis
```
</details>

It takes over 200x times for the max one (`nb list`) and the min one (`nb run ls`).

As similar tools, I prefer [mattn/memo][] for taking notes. This is written by Go, and has similar (less) features with `nb list`, listing notes with parsing titles from the fiestline of each file.

[mattn/memo]: https://github.com/mattn/memo

<details><summary>tests for mattn/memo on the same directory</summary>

```sh
# count notes
> memo list | wc -l
    2814

# list filenames
> time memo list > /dev/null

________________________________________________________
Executed in   17.13 millis    fish           external
   usr time    6.73 millis  119.00 micros    6.61 millis
   sys time    7.29 millis  1093.00 micros    6.20 millis

# list the title from each file (parsing the first line)
> time memo list --format '{{.Title}}' > /dev/null

________________________________________________________
Executed in  256.92 millis    fish           external
   usr time   59.07 millis  146.00 micros   58.92 millis
   sys time  171.45 millis  1262.00 micros  170.19 millis
```
</details>

It takes only **0.2s** to parse over 2000 files! (even with my slow macOS!)

Of course, this is very rough comparison. mattn/memo is much simple tool and has less features than `nb`. But I wish `nb` could show files with titles much faster (&lt; 1s) even with over 2000 notes...

**Comment by xwmx** [comment]
Everything is a Unix program. That’s a core theme of this project.

It’s better to think of `nb` as being in no language. It does as little as possible itself, and it can leverage any tool and any language to perform operations. So it starts with the baseline of using the available tools and languages in base unix / linux environments. When preferred tools are available, it automatically upgrades to those tools.

For example, `nb search` fully supports POSIX `grep` by default, which is less performant than modern search tools. When the modern search tools `rg`, `ack`, or `ag` are available, `nb` automatically uses one of them instead, and as you can see, `nb search` is fast with the optional dependencies. If something better comes along, `nb` can use that, too. As you can see, `nb` itself is just orchestrating between tools.

Also, I just tested on a 2013 MacBook Pro:

```bash
> nb count
2497

> time nb list > /dev/null
20.87s user 12.58s system 93% cpu 35.820 total

> time nb list --no-id > /dev/null
9.85s user 3.51s system 98% cpu 13.503 total

> time nb list --no-id --filenames > /dev/null
3.19s user 0.22s system 101% cpu 3.377 total

> time nb list --no-id --filenames --no-indicators > /dev/null
0.45s user 0.17s system 104% cpu 0.592 total
```

So I don’t know why it’s twice as slow for you. If the documents are fully in CJK characters then it’s possible that is a slow regular expression operation, but I’ll have to generate a notebook of CJK lorem ipsum and test.

I tried installing memo, but couldn’t get it to print output when running it in that directory of 2497 markdown files. Note in those benchmarks you have a lot of time spent system (12.58s system) because of the filesystem calls. I’m googling now and not seeing anything that indicates that golang eliminates the file system overhead. I’ve also tested getting the ids with sqlite and it’s a pretty slight difference.

I’m going to go ahead and close this. If you have a tool or strategy for increasing performance here, I prefer communicating in or directly about actual code.

**Comment by xwmx** [comment]
I made some performance improvements over the past few days.

Here are three runs of `nb list` on version 5.7.2 from earlier this week:

```bash
> time nb list > /dev/null
18.62s user 11.20s system 96% cpu 30.774 total

> time nb list > /dev/null
18.79s user 11.12s system 96% cpu 30.895 total

> time nb list > /dev/null
18.49s user 10.93s system 96% cpu 30.390 total
```

Here are three runs of `nb list` on version 5.7.7 from today:

```bash
> time nb list > /dev/null
13.48s user 6.94s system 92% cpu 22.062 total

> time nb list > /dev/null
11.20s user 5.53s system 96% cpu 17.283 total

> time nb list > /dev/null
11.18s user 5.44s system 96% cpu 17.194 total
```

So it should feel snappier. I'm continuing to think about and improve this.

**Comment by delphinus** [comment]
I found also significant improvement (71s → 49s). Good job!
