### ISSUE TITLE
Error with nb completions for zsh

### ISSUE THREAD

**Issue by Marthym** [xwmx/nb#51]
Using `zsh` the completion give on error

```
_cache_completions:54: le fichier existe: /home/user/.nb/.cache/nb-completion-cache-zsh
_cache_completions:54: file exists: /home/user/.nb/.cache/nb-completion-cache-zsh
```

**Comment by xwmx** [comment]
Thanks for the heads up! This should be resolved now. You can update the completion scripts using:

```bash
nb completions uninstall && nb completions install --download
```

or if `sudo` is required:

```bash
sudo nb completions uninstall && sudo nb completions install --download
```

Please let me know if you run into additional issues with this.

**Comment by Marthym** [comment]
Hi,

The `install --download` always install old version but if I made the change manually it was ok

Thx
