### ISSUE TITLE
Support organization of files in folders

### ISSUE THREAD

**Issue by goodevilgenius** [xwmx/nb#56]
The documentation mentions folders as a type, but there's no support for creating folders. Additionally, if there any files in folders, they're not recognized at all.

I would like to be able to do something like the following:

```shell
$ nb folder add work
# does `mkdir work` from notebook
$ nb rename 3 work/
# Does `mv <file-for-3> work/`
$ nb search <query>
# Searches all files recursively
$ nb ls 
# Lists all top-level files and folders
$ nb ls work/
# Lists every file within work/ folder
$ nb folder add work/in-progress
# does `mkdir -p work/in-progress` from notebook
```

Here's a few things I've tried:

```shell
$ cd ~/.nb/<notebook>
$ mkdir work
$ nb rename 3 work/filename.md
# This works, and moves the file, but there's an error
# sed: -e expression #1, char 17: unknown option to `s'
```

**Comment by xwmx** [comment]
Quick screenshot of the new folder breadcrumbs in `ls` in the [folders branch](https://github.com/xwmx/nb/tree/folders):

<img width="657" alt="folder-crumbs" src="https://user-images.githubusercontent.com/1246/98018318-42af4180-1db5-11eb-9e54-d409d7594018.png">

**Comment by goodevilgenius** [comment]
Wow! This is great. I'm trying out the `folders` branch, and it's working great for me.

**Comment by xwmx** [comment]
@goodevilgenius Awesome. I feel like it's about 80% done. I'm making some other major upgrades in the process, like combining `move` and `rename` and supporting complex selectors in `add`.

**Comment by xwmx** [comment]
Folders can be identified by either name or id, and a trailing slash runs `ls` in the folder:

```bash
> nb example:
example · home
--------------------
[3] document.md
[2] 📂 Example Folder
[1] sample.md

> nb show example:Example\ Folder/
example · home
--------------------
Example Folder /
--------------------
[2] two.md
[1] one.md

> nb show example:2/
example · home
--------------------
Example Folder /
--------------------
[2] two.md
[1] one.md
```
Names and ids can be mixed and matched within a path.

**Comment by xwmx** [comment]
This is still a work in progress, but stable enough that I merged it into the master branch. `add`, `list`, `show`, `move`, `edit`, `export`, and `index` have folder support with test coverage, though I'm aware of a couple things like messages that need to be updated. Several of the other subcommands like `bookmark`, `search`, and `history` don't support folders yet, but continue to function normally otherwise.

**Comment by xwmx** [comment]
Version 6 has been released with this feature. Folders now work throughout the application. There information in the README:

https://github.com/xwmx/nb#-folders

@goodevilgenius Thanks for bringing this up! This was a fun feature to build.

**Comment by goodevilgenius** [comment]
Awesome. Works great!
