### ISSUE TITLE
Install Problems and Solutions on Ubuntu with Sudo Steps

### ISSUE THREAD

**Issue by tjortho** [xwmx/nb#58]
Ubuntu 20.04
NVM used to install node v15.0.1
`npm install -g nb.sh` used to install nb

1) nb works after install  
2) But the sudo steps cannot be executed because 'nb' command is not found under sudo
`sudo nb completions install`
`sudo nb env install`

`sudo: nb: command not found`

`env | grep ^PATH` shows that the node bin directories are not part of the PATH under sudo and haven't been set (I'm guessing this is for security reasons?)

Workaround: (Assumes this is just a one time need, and not ongoing)

I would suggest adding the following into the Ubuntu installation directions for those who may have trouble installing like I did:

**If you receive an error of** `sudo: nb: command not found` **this means that the sudo environment does not include the path to your installed version. You will need to execute the sudo steps locally in the directory of the executable file since it is not globally available under sudo.**

- Type `which nb` to find out the location of the executable file

- `cd directory_listed_above`

- `sudo ./nb completions install`

- `sudo ./nb env install`

Thanks for your hard work. I hope this helps others install on their systems a bit easier and helps increase adoption.

**Comment by xwmx** [comment]
Thank you for the information. I was able to reproduce the configuration and associated issue. After experimenting, it looks like `sudo "$(which nb)" completions install` and `sudo "$(which nb)" env install` work successfully, so I updated the post-install instructions to use this command. Please let me know if you run into additional issues with this.

Thanks again!
