### ISSUE TITLE
Support show note using glow

### ISSUE THREAD

**Issue by koolay** [xwmx/nb#62]
[glow](https://github.com/charmbracelet/glow) is a  beatiful tool for rendering markdown.
It'll be wonderful that `nb` works with `glow`.

**Comment by xwmx** [comment]
Indeed. Looks interesting. I'm working toward having configurable viewers for `nb show`.

**Comment by kdkasad** [comment]
> Indeed. Looks interesting. I'm working toward having configurable viewers for `nb show`.

I think this is a better idea than just supporting `glow`. There's a setting for configuring the editor command, so that same approach could be used for the pager to allow for using `less`, `glow`, or even custom scripts.

**Comment by lousyd** [comment]
I would like to use `cat` as the pager for some file types.

**Comment by Enqueued** [comment]
For reference when you pipe `nb show #` into `glow` you recieve color codes as pure text with no text highlighting or coloring.

```
Example:

  [38;2;248;248;242mEasy to use[0m
  [38;2;248;248;242mQuick to make tools[0m
  [38;2;248;248;242mTied into Amazon echo system [0m
  [38;2;248;248;242mGraphs and charts are ssr and can be whipped up via amplify studio[0m
```

**Comment by jpporta** [comment]
I am using this:
`nb s --print --no-color <note-number> | glow`

And on my .zshrc I created a function to insert the note number with a new command
```
function nbs() {
    if [ "$1" != "" ]
    then
        nb s --print --no-color "$1" | glow
    else
    fi 
} 
```

Now I just do `nbs <note-number>` and it will pipe to glow

**Comment by xwmx** [comment]
As of version 7.7.0, there is now a [`$NB_MARKDOWN_TOOL`](https://github.com/xwmx/nb#nb_markdown_tool) configuration variable that can be set to `bat`, `glow`, `mdcat`, `mdless`, or `mdv`.

To use `glow` as the viewer for Markdown items in `show`, add the following to your `~/.nbrc` file:

```bash
export NB_MARKDOWN_TOOL="glow"
```

Let me know if you run into any issues with this feature. Thanks!

**Comment by andrew-manger** [comment]
@xwmx I can file a new issue for this if you'd like; I am having issues with glow. It displays each line with an additional 9-12 line breaks between each.

This is what happens when glow is set as the markdown tool and I use `nb show {#}`:
![Image](https://github.com/user-attachments/assets/927a665f-a44c-4f76-b941-cd3153f44c99)

When I use glow directly, this is what I get:
![Image](https://github.com/user-attachments/assets/3173bfef-d244-4fb7-81c1-b4b23859bed2)

**Comment by xwmx** [comment]
@andrew-manger Does the output of the following command include the extra lines?

```bash
cat `nb show 2 --path` | glow --pager
```

**Comment by andrew-manger** [comment]
@xwmx nope, that worked great!

![Image](https://github.com/user-attachments/assets/a6c7d75e-9303-45a7-9135-b6317d26d468)

**Comment by xwmx** [comment]
@andrew-manger So far, I've been unable to reproduce the issue or identify the cause. [`cat "${_target_path}" | glow --pager`](https://github.com/xwmx/nb/blob/4d238db2bdac4f88fbe2c96794983f215ae6f1f1/nb#L19198) seems to be the entire effective command, so it's not immediately clear to me where the additional lines are coming from. I'll keep thinking about it.

**Comment by andrew-manger** [comment]
@xwmx, interesting, please lmk if there is any other logs or troubleshooting I can help provide! I love nb and want to contribute in any way I can

**Comment by xwmx** [comment]
@andrew-manger I wonder if it's an older version of glow and / or if there's something specific to that system's configuration. What is the `glow --version` on the Debian system? I don't have a Debian system immediately available, but I just tried on Ubuntu with glow version 2.0.0 installed via snap and it worked as expected without the extra lines. `glow --version` is also 2.0.0 on my mac.
