### ISSUE TITLE
Searching by multiple tags?

### ISSUE THREAD

**Issue by johnhayesio** [xwmx/nb#65]
Unless I missed something, searching by multiple tags does not work for me. I have used the search as stated in the documentation `nb q/search '#article #medium' -l`, but this does not work and returns nothing although I have many bookmarks tagged with article and medium in the same bookmark.

**Comment by johnhayesio** [comment]
It seems that it works as long as the tags are searched in the order in which they appear in the bookmark, but searching in an alternate order doesn't return anything. I tried `nb q '#medium #article' -l` and it actually returns articles. But this does not work if the tags are not consecutive in order.

**Comment by xwmx** [comment]
Correct, `AND` queries are not yet supported, but I’m working toward it.

My understanding / recollection is that doing this kind of query with `grep`-style tools requires running the query multiple times to first filter a list of filenames and then run the filenames though the final query to get the results. So I guess it's just a matter of implementing that with each of the search tools in the `_search()` function.

Regarding the described behavior, the quotes create a phrase / pattern search, so it's returning the hit for the string and line matching that phrase / pattern. When `AND` queries are implemented I expect that `nb search` will accept multiple phrases for these queries, e.g., `nb q "example multi-word phrase" "#tag1"` would return all documents containing both "example multi-word phrase" and "#tag1".

**Comment by johnhayesio** [comment]
Appreciate that explanation. I was wondering how the search works. For now, I am just using ripgrep to search for tags and then having to work around to get the file to open.

**Comment by xwmx** [comment]
OK, `nb` should now have full support for both `AND` and `OR` queries.

`AND` queries can be specified by either passing multiple query arguments to `nb search` or using the `--and` option (example use the `q` shortcut for `search`):

```bash
# search for the "#example" AND "#demo" tags with multiple arguments
nb q "#example" "#demo"

# search for the "#example" AND "#demo" tags with option
nb q "#example" --and "#demo"
```
`OR` queries can be specified using by separating terms / tags in a single argument with a pipe character `|` or with the `--or <query>` option.

```bash
# search for "#example" OR "#sample" with argument
nb q "#example|#sample"

# search for "#example" OR "#sample" with option
nb q "#example" --or "#sample"
```

This feature is available in the latest versions of the git repository and will be available in the next point release.

**Comment by xwmx** [comment]
Version 6 has been released and includes this feature. @johnhayesio  Thanks!
