### ISSUE TITLE
Command to clean up index files: remove empty lines

### ISSUE THREAD

**Issue by goodevilgenius** [xwmx/nb#67]
After a bunch of adds/deletes, particularly if sometimes adding to a remote repo with a different app (I use [`GitJournal`](https://github.com/GitJournal/GitJournal) on Android to manage my notebook), the `.index` files can end up with a bunch of empty lines, and you have a bunch of skipped nubmers when doing `nb ls`.

Obviously, this is by design, so that an index `n` always refers to the same item.

However, I've found that I like to clean that out from time to time so that I don't have a bunch of skipped numbers.

I added a git alias within my notebook like this:

```
[alias]
	crunch = !find . -name .index -exec sed -i '/^\\s*$/d' {} +
```

That way, I can run `nb git crunch`, and it cleans out those empty entries.

It would be nice if this option were built into `nb`.

**Comment by xwmx** [comment]
Interesting. There's actually a [`nb index rebuild` subcommand](https://github.com/xwmx/nb#nb-help-index) that deletes the index, rebuilds it, and creates a new git commit. There's no confirmation prompt and using `index add`, `index delete`, and `index update` directly can corrupt the index, so I don't really advertise this subcommand, but it should do what you are looking for.

**Comment by goodevilgenius** [comment]
@xwmx That's what I was looking for. I must've missed it. Thanks!
