### ISSUE TITLE
Allow to specify an user-agent when downloading web content using wget (or whichever tool is used by nb) in order to avoid 403 errors.

### ISSUE THREAD

**Issue by lgvld** [xwmx/nb#72]
Hi !

I’m considering switching to `nb` for the management of my bookmarks. Thank you very much for this clean and consise tool, I love it. 😍

But in my preliminary tests, an error occured when bookmarking a webpage (it was only my fifth bookmark, so I guess it’s a quite common error). To recreate this error, please try to bookmark the webpage having the following URL:

[https://riding-through-this-world.com/voyages/gr10/](https://riding-through-this-world.com/voyages/gr10/)

This is the result I get:

```
[5] 🔖 403 Forbidden (riding-through-this-world.com)
```

So the content of the webpage is not really bookmarked, as `nb` only sees a 403 error. Using `wget` (without any parameter) also gives us a 403 error. 

A simple workaround, using `wget`, would be to specify a user-agent -- i.e. faking a genuine browser -- by doing:

```
wget https://riding-through-this-world.com/voyages/gr10/ --user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
```

So...

Do you think it would be useful to add this setting to `nb` ? What would be the best ? Add a setting, and let the user choose if he wants to specify a user-agent (less usable, I guess)? Hardcode a fake default user-agent into `nb`? Detect installed browsers on the system running `nb`, and send a corresponding user-agent when doing HTTP resquests (as `nb` already does, I mean defaulting to different tools for an operation)?

Another few questions:
- Don’t you think you should add an option enabling full download of a webpage when bookmarking (what we get using `wget -r`, i.e. recursive download)? This way `nb` would _really_ archive webpages, and not just store the source. 
- If the answer to the former question is no, then what would be the _good_ way to add such a feature in `nb`? Would a plugin be sufficient? Can a subcommand specified by a plugin replace an already existing subcommand?
- Also why does `nb` allow bookmarking an already-bookmarked URL? Is there not a way to simply replace or update a bookmark?

Thank you very much for your time.

Best regards.

__EDIT__: My sixth (not kidding 😅) bookmark also leads to a surprising error -- which disappear when specifying an user-agent. Try bookmarking the following URL:

https://www.wordreference.com/enfr/contemptible

**Comment by xwmx** [comment]
@lgvld, glad you like it!

> My sixth (not kidding 😅) bookmark also leads to a surprising error -- which disappear when specifying an user-agent. Try bookmarking the following URL:
>
> https://www.wordreference.com/enfr/contemptible

Very strange!

I just added the ability to specify a user agent by setting the `$NB_USER_AGENT` environment variable to a desired value. This assignment can be added to `~/.nbrc` for persistence (open with `nb settings edit`):

```bash
# ~/.nbrc

export NB_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"
```

The user agent can also be specified on a per-command basis by prepending the variable assignment to the comment in the shell :

```bash
NB_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36" nb https://example.com
```

I've confirmed that both of the above links appear to save properly when the user agent is set using this method in `~/.nbrc`.

This is now available in the latest version in git and will be in the next point release. Let me know if you run into any issues with it.

> Don’t you think you should add an option enabling full download of a webpage when bookmarking (what we get using wget -r, i.e. recursive download)? This way nb would really archive webpages, and not just store the source.

Yeah, I definitely intend to have `nb` support this either in the core or as a plugin. I have some ideas about how to implement it and am working on prerequisite features, notably better folder support. There are a couple other issues with some discussion about organizing assets: #54 #68 

> Also why does nb allow bookmarking an already-bookmarked URL? Is there not a way to simply replace or update a bookmark?

I haven't really thought about this. Currently `nb` just using the most straightforward implementation. I'll keep this in mind and think through the UX.

Please let me know if this works and we can close this, or if you run into any issues with this!

**Comment by lgvld** [comment]
Great news! 😊 Thank you very much for your time and investment in this project.

Regarding the save of a complete webpage, as I told you, passing the `-r` option to `wget` does the job (the directory hierarchy is recreated). Related: the [SingleFile extension for Firefox](https://addons.mozilla.org/fr/firefox/addon/single-file/) is perfect to save a webpage, as everything is packed in a single HTML file.

> Yeah, I definitely intend to have nb support this either in the core or as a plugin. I have some ideas about how to implement it and am working on prerequisite features, notably better folder support. There are a couple other issues with some discussion about organizing assets: #54 #68

Automatically updating URL (or prompting the user before doing so) when encountering an already bookmarked URL would be an interesting feature for me as I can be a big data hoarder. Sometimes I totally forget about stuff I bookmarked a few months before...

Another thank you.

Regards.
