### ISSUE TITLE
Add option to prevent syntax highlighting

### ISSUE THREAD

**Issue by kdkasad** [xwmx/nb#77]
Highlighting markdown syntax in notes is very helpful for reading them, but extremely annoying when trying to pipe notes into other commands. It would be great if there was an option to `nb show` that would prevent syntax highlighting.

**Comment by xwmx** [comment]
Hi @kdkasad, there is actually a global `--no-color` option that should work with every `nb` command. For example, to print the content of item "12" to standard output with no color highlighting:

```bash
nb show 12 --no-color --print
```

Let me know if you run into any trouble with this!

**Comment by kdkasad** [comment]
Yes, it works. I thought I already tried that but I guess not. Thanks!

**Comment by xwmx** [comment]
Good call. Done.
