### ISSUE TITLE
Decryption fails in Big Sur MacOS

### ISSUE THREAD

**Issue by bscott** [xwmx/nb#78]
After upgrading to Big Sur on MacOS, Decryption of notes fail:

`! Decryption error.`

Works on OS'es Prior, Windows & Linux

Possible issue with openssl libs in new update.

**Comment by xwmx** [comment]
Hi @bscott!

I've been able to confirm that tests are passing on [a fresh install of Big Sur via GitHub Actions](https://github.com/xwmx/nb/runs/1498614006?check_suite_focus=true), so I'm unable to replicate the issue and determine the cause so far.

The [encryption](https://github.com/xwmx/nb/blob/780568b497dd97eb5c0acbaa3790dd4436fc96ad/nb#L1262) and [decryption](https://github.com/xwmx/nb/blob/780568b497dd97eb5c0acbaa3790dd4436fc96ad/nb#L1025) functions use the `openssl` command line tool directly, and this error suggests that the `openssl` command encountered an error.  The current decrypt function suppresses errors from the `openssl` tool, but you can try running [the `openssl` decryption command](https://github.com/xwmx/nb/blob/780568b497dd97eb5c0acbaa3790dd4436fc96ad/nb#L1072) directly in the command line. The following version should work with the example input and output file paths updated to the appropriate paths:

```bash
openssl enc -d -aes-256-cbc -in /example/path/to/encrypted-file.md.enc -out /example/path/to/output-file.md 
```

The full path to an item in `nb` can be obtained with `nb show --path`:

```bash
# show the full path to note 12 in the current notebook
nb show 12 --path
```

If OpenSSL is installed via Homebrew with the default options, another thing to try might be reinstalling it with: `brew reinstall openssl`

Let me know if any of this helps!

**Comment by Marthym** [comment]
I have the same with GPG on linux

```
! Unable to decrypt file.
```

When try to edit encrypted file. When I decrypt file using gpg directly it's ok

```
gpg --output my-note.md --decrypt my-note.md.enc
```

**Comment by xwmx** [comment]
@Marthym, thanks for the heads up. The error you encountered looks like it's due to [the `file` command response](https://github.com/xwmx/nb/blob/master/nb#L1052) not matching either "GPG" or "openssl", which is the main way `nb` uses to detect encrypted files and the tool used to encrypt them.

There are a few [encrypted file type tests](https://github.com/xwmx/nb/blob/master/test/helpers.bats) that intermittently fail, apparently when calling the `file` command ([man page](https://linux.die.net/man/1/file), [wikipedia](https://en.wikipedia.org/wiki/File_(command))). These tests do not always fail, and usually will pass on the same system on other test runs, so it doesn't appear to be a configuration issue. I've experimented with `file` to try to get it to print an unexpected response, even calling it many times in a row using a sequence, but it always appears to return a correct response when called directly.

@Marthym Could you try running the `file` command with the path of the encrypted file and copy and paste the output here? For example, the following command should work with "123" replaced with the id of the encrypted file:

```bash
file "$(nb show 123 --path)"
```

**Comment by Marthym** [comment]
With bash
```shell
$ file "$(nb show 123 --path)"
/home/myuser/.nb/home/myfile.md.enc: PGP symmetric key encrypted data - AES with 256-bit key salted & iterated - SHA512 .
```

**Comment by xwmx** [comment]
@Marthym Awesome. Thanks! Yeah, in this case, it looks like I can just update `nb` to match both "PGP" and "GPG" in the responses, and that should resolve the error you encountered. I'll do that shortly.

I think this error is different from the one I mentioned and the one on Big Sur, but it could be related. I'll keep looking.

**Comment by bscott** [comment]
Thanks @xwmx , I did a fresh install and came with the issue I reported. I'll see if I can dig into the logs to retrieve more info unless you think your recent updates might if fixed. 

Also, is that a go client I see in the works in the base of the repo :)

**Comment by xwmx** [comment]
@bscott I just looked into background information and it looks like `openssl` might not be completely installed on macOS by default [[1]](https://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html) [[2]](https://forums.swift.org/t/mac-big-sur-error-using-openssl-to-generate-private-key-for-jwt/42087). I've checked a local machine running Catalina and `openssl` is located at `/usr/bin/openssl` which is a [protected](https://support.apple.com/en-us/HT204899) macOS system location, so it was installed by an Apple installer, but maybe it was installed with Xcode.

Currently my only access to Big Sur is with GitHub Actions. There are a few things I can think of to try.

The following command should tell us where the current `openssl` executable is located and whether it's a symbolic link or installed with Homebrew:

```bash
ls -la "$(which openssl)"
```

If there is an error like `not found: No such file or directory`, then it probably needs to be installed. It's possible it comes with the Command Line Tools for Xcode, which can be installed with `xcode-select --install`, [developer.apple.com/downloads](https://developer.apple.com/download/more/) or [Xcode](https://apps.apple.com/us/app/xcode/id497799835).

If `openssl` is not installed either by default or the Command Line Tools for Xcode, then I would recommend installing it via [Homebrew](https://brew.sh/):

```bash
brew install openssl
```

I'm still looking into this.

> Also, is that a go client I see in the works in the base of the repo :)

Indeed, it is. 😁

**Comment by bscott** [comment]
Indeed, I'll give it a try and updates you.

**Comment by truatpasteurdotfr** [comment]
I think I have the "same" identification error but on CentOS-7:
```
[tru@sillage home]$ type gpg file
gpg is hashed (/usr/bin/gpg)
file is hashed (/usr/bin/file)
[tru@sillage home]$ rpm -qf /usr/bin/gpg /usr/bin/file
gnupg2-2.0.22-5.el7_5.x86_64
file-5.11-37.el7.x86_64
[tru@sillage home]$ nb show 4
Password: 
! Unable to decrypt file.
[tru@sillage home]$ nb show 4 --path
/home/tru/.nb/home/20210222150436.md.enc
[tru@sillage home]$ file /home/tru/.nb/home/20210222150436.md.enc
/home/tru/.nb/home/20210222150436.md.enc: data
[tru@sillage home]$ gpg --decrypt /home/tru/.nb/home/20210222150436.md.enc
gpg: AES256 encrypted data
gpg: encrypted with 1 passphrase
secret
```

**Comment by Jacke** [comment]
Got the same issue. 

```
╰─ openssl version
LibreSSL 2.8.3
```
while I'm trying to decrypt I got:
```
enter aes-256-cbc decryption password:
bad decrypt
4418369196:error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt:/System/Volumes/Data/SWE/macOS/BuildRoots/ff60e5d618/Library/Caches/com.apple.xbs/Sources/libressl/libressl-68/libressl-2.8/crypto/evp/evp_enc.c:521:
```

the current **workaround** is to pass the md flag explicitly (because they change default value of -md flag from md5 to sha256)

```
openssl enc -d  -md sha256-aes-256-cbc -in /example/path/to/encrypted-file.md.enc -out /sample/path/to/output-file.md 
```

Similar:
https://github.com/libressl-portable/portable/issues/378#issuecomment-355908517

 keeps give us more problems than solutions

**Comment by xwmx** [comment]
@Jacke, thanks for the crucial information! This should be working now as of version 6.7.9. Files are now always encrypted with `-md sha265`. When decryption fails, it falls back to `-md md5`. I've confirmed that items encrypted on macOS Mojave can be opened on macOS Monterey. Please let me know if there are any more issues with this.

**Comment by Jacke** [comment]
@xwmx Thanks for the fixes.
