### ISSUE TITLE
user-only install  failed!

### ISSUE THREAD

**Issue by FYYFU** [xwmx/nb#79]
i follow the user-only installation to install nb on a server. i successed install nb and input the user name and gamil. then i user the commond `nb set editor` and chooose `nano`.  everything seems ok. I can use nb to create and writer a  .md file.   but when i restart a shell and connection the the server again. I failed to use 'nb'.  the error is :
```python
The program 'nb' is currently not installed. To run 'nb' please ask your administrator to install the package 'nanoblogger'
```
i sure it works will when i successful install it and nothing changed expect restart a shell to connection to the server again.

**Comment by xwmx** [comment]
Hi @FYYFU! It sounds like the directory containing `nb` is not assigned in the `$PATH` environment variable during shell startup. If you installed `nb` using the command from the README, then it should be at `~/bin/nb` and `~/bin` (equivalent to `$HOME/bin`) should be in `$PATH`.

To have this assigned on shell startup, add the following line to `~/.bashrc` if you are using Bash as your primary shell, or `~/.zshrc` if you are using Zsh:

```bash
[[ -d "${HOME}/bin" ]] && export PATH="${HOME}/bin:${PATH}"
```

After reloading the shell, you should be able to use `nb`.

Let me know if this helps!

**Comment by FYYFU** [comment]
> Hi @FYYFU! It sounds like the directory containing `nb` is not assigned in the `$PATH` environment variable during shell startup. If you installed `nb` using the command from the README, then it should be at `~/bin/nb` and `~/bin` (equivalent to `$HOME/bin`) should be in `$PATH`.
> 
> To have this assigned on shell startup, add the following line to `~/.bashrc` if you are using Bash as your primary shell, or `~/.zshrc` if you are using Zsh:
> 
> ```shell
> [[ -d "${HOME}/bin" ]] && export PATH="${HOME}/bin:${PATH}"
> ```
> 
> This line checks whether a `~/bin` directory exists and, if it does, it adds that directory as the first search location in `$PATH`.
> 
> After reloading the shell, you should be able to use `nb`.
> 
> Let me know if this helps!

Thanks a lot! it works will now.  i used to add  something into the `~/.bashrc`. i think it might be wrong because i forgot to add `""` to the PATH(eg: `export PATH = $HOME$/nb:${PATH}`)

**Comment by xwmx** [comment]
Glad to hear it! Let me know if you run into any more issues with this. Thanks!
