### ISSUE TITLE
git integration only supports global name & email, not per-repo.

### ISSUE THREAD

**Issue by birlorg** [xwmx/nb#8]
in `_git_required()` you require git to have a global username and email address set.

it looks like if you run `git config user.name` from within the repo, then the repo-specific config will be read and will return specific username and email.

I think if https://github.com/xwmx/nb/blob/master/nb#L1164 was wrapped around a cd to the git repo, that would fix it. But I think you support multiple notebooks and I haven't read into nb how you do that, so I leave that as an exercise for you, if you choose to accept this as an issue.

locally I just deleted most of the `_git_required` function as a work around.

you also set the name & email globally, but that is probably a sane default.

Anyways, still playing with this, but so far seems pretty neat! Thanks for the code!

**Comment by xwmx** [comment]
I'm thinking maybe the git prompt of part of `_git_required` would be extracted to a new function (or, better yet, maybe part of the `nb git` subcommand)  named something like like `_git_config`. Then a new `nb notebooks config` subcommand (name TBD) could be used to run `_git_config` within the current or a selected notebook, and `notebooks add` could take an optional `--config` flag (name TBD) to run  `_git_config` when creating the notebook.

I'll think about this a bit more!

**Comment by jaybe-jekyll** [comment]
Hello. I too would like to see option to configure separately from global certainly and ideally the option for per-local-notebook.

In the meantime the following seems to work:

```sh
cd ~/.nb
cd home
git config --worktree user.name "Global Notebook User"
git config --worktree user.email "me@example.org"
```

One could then optionally fully remove ~/.gitconfig if desired and `nb` will no longer complain and drive you through "setup" again.

`rm -iv ~/.gitconfig` # if desired

**Comment by lunaryorn** [comment]
I'd also appreciate if this check would respect repo-local configuration, or could be disabled altogether.   I need to use different mails for different repos (for various reasons), and use Git-dir derived config includes to change the mail address depending on the path.  `git` has a `-C` option since quite a while to run a command in a specific directory, so I think `git -C "$NOTEBOOK_DIR" config user.email` would be sufficient wouldn't it?

I'd also be fine if there was a flag for `~/.nbrc` to skip this check altogether; `git commit` will fail anyway if there's no mail address set, so there's no risk of doing anything wrong, meaning that `nb` could just trust me to have Git setup correctly :slightly_smiling_face:

**Comment by khimaros** [comment]
> I'll think about this a bit more!

any further thoughts on this? if you have a design you're happy with, i'd be happy to send a PR.

**Comment by xwmx** [comment]
The commit author for a notebook can now be configured with `nb notebooks author` on existing notebooks and the `--author`, `--email <email>`, and `--name <name>` options on `nb notebooks add`, `nb notebooks init`, and `init`.

Information in the README:

https://github.com/xwmx/nb#-revision-history

This is available in the latest versions of the repository and will be in the next point version, 6.0.0..

**Comment by xwmx** [comment]
Version 6 is available with this feature. There is another open issue about adding the ability to turn off git (#97). Let me know if you run into any trouble with this!

**Comment by CaptainQuirk** [comment]
Even if the per notebook git configuration works, it is still required to have a global name and email configured. I think that asking for missing git credentials should only happen when execute commands that actually rely on git to either display history or change the content of a notebook
