### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by jeffskelton3** [xwmx/nb#81]
I hope opening an issue like this isn't annoying or anything. I just wanted to send a big thank you to all the contributors on this project. I've been using it extensively the past few months and I just keep finding more things to love about it. 

I don't see a link on your repo page, but if there's a way to donate that I am not seeing LMK. I realize its not much but I feel like this software is good enough to pay for. Keep up the great work!

**Comment by xwmx** [comment]
You're welcome, and thank you so much for the words of encouragement! 😊 I will look into setting up GitHub sponsors, etc.

**Comment by jeffskelton3** [comment]
Awesome! Closing this issue so it doesn't clog up your feeds. Thanks again!
