### ISSUE TITLE
Installation on FreeBSD

### ISSUE THREAD

**Issue by hagenbauer** [xwmx/nb#83]
I am trying to install nb on my FreeBSD 12.2 box. I am already using it on Ubuntu.

`git clone https://github.com/xwmx/nb.git
Klone nach 'nb' ...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 17127 (delta 20), reused 25 (delta 12), pack-reused 17093
Empfange Objekte: 100% (17127/17127), 4.72 MiB | 1.42 MiB/s, fertig.
Löse Unterschiede auf: 100% (11799/11799), fertig.
~/installation]$ cd nb
 ~/installation/nb]$ sudo make install
install nb /usr/local/bin
install bin/bookmark /usr/local/bin
./nb env install
*** Error code 1

Stop.
make: stopped in /usr/home/hbauer/installation/nb
`

Any ideas where to look?

**Comment by xwmx** [comment]
Hi @hagenbauer, this error should be resolved in the latest version in the git repository, so if you update the clone and try again it should work. Let me know if you still run into issues with it!

**Comment by hagenbauer** [comment]
great. its working not. that was fast. greatly appreciated. thank you
