### ISSUE TITLE
nb show problem:  less -X: command not found

### ISSUE THREAD

**Issue by rhaynes74** [xwmx/nb#84]
Hi folks, I usually use nb open #, but I thought I would start using nb show # for a quick look, 

Unfortunately, on my mac, nb open 1 gives:
/usr/local/bin/nb: line 2318: less -X: command not found

nb has been installed with homebrew. 

Best,
R Haynes

**Comment by xwmx** [comment]
Hi @rhaynes74! It looks like the `$PAGER` environment variable is set in your environment to `less -X` and the way that `nb` calls the pager doesn’t work properly with `$PAGER` values containing spaces. I’ll have to update `nb` so it handles these values. If this indeed the cause, you can probably circumvent it by adding `export PAGER=“less”` to your `~/.nbrc` file, which you can open in your editor with `nb settings edit`

Let me know if this helps!

**Comment by kdkasad** [comment]
I think there's a better solution. `less(1)` will automatically take options from the `$LESS` environment variable according to the man page.

So set your environment variables as follows:
```sh
export PAGER=less
export LESS="-X"
```

**Comment by rhaynes74** [comment]
Thanks folks, I have it working again!

**Comment by xwmx** [comment]
@rhaynes74 Awesome. Thanks for the tip, @kdkasad!
