### ISSUE TITLE
git required should respect includes

### ISSUE THREAD

**Issue by schemar** [xwmx/nb#86]
I have a `~/.gitconfig` file with an include for my user email:
```ini
[include]
  path = ~/.gitconfigemail
```

That file only includes:
```ini
[user]
  email = name@example.com
```

The output of the git config with and without `--includes`:
```shell
$ git config --global user.email

$ git config --global --includes user.email
name@example.com

$
```

I expect `nb` to read the user email from the included file, but instead it prompts for the email and forces setting it in `~/.gitconfig` directly.

As an easy fix, that I could create a PR for, `nb` could use the `--includes` flag in the git requirement checks in lines 3343 ff.: https://github.com/xwmx/nb/blob/master/nb#L3343

**Comment by xwmx** [comment]
@schemar Thanks! Yeah, if you have a chance to do a pull request before I get to it, that would be great.

**Comment by schemar** [comment]
I had the time :blush: It is a very tiny change.
