### ISSUE TITLE
A way to list tags?

### ISSUE THREAD

**Issue by nathansquan** [xwmx/nb#99]
Thank you for such an amazing command line note taking program!

I see there is a way to search for tags which is very helpful. Is there a way to list tags that you have created already? If not, it might be a good feature to implement to allow users to have consistent tags across notes.

**Comment by xwmx** [comment]
@nathansquan Glad you like it!

I just added an implementation of this that can be used with `nb --tags`, `nb ls --tags`, `nb list --tags`, and `nb search --tags`. They all use `search --tags` so you can pass a notebook and/or folder like `nb notebook:folder/ --tags` and list tags from all notebooks with `nb --tags --all`.

This implementation currently performs a full text search, so tags from within bookmarked content are included. I'll have to think about how to exclude them.

**Comment by cainwatson** [comment]
@xwmx This would be great! I've gotten to a point where I don't remember all the tags I've used, so this would be very helpful.

On that note about tags with other tag-matching strings, how would you feel about adding an option to let users decide what identifier to use for tags? Perhaps I could change my identifier to `+` (e.g. +tag1 +tag2) since that shows up less in my notes and bookmarks.

**Comment by nathansquan** [comment]
@xwmx Just cloned the repo and it works great! Thanks for the quick implementation.

**Comment by xwmx** [comment]
I was able to exclude the bookmarked content. Currently it still includes tags defined in other bookmark sections, so tags can be defined in comments. There are some cases (for example, with bookmarked GitHub issues) where numbers (e.g., #99) are recognized as hashtags. This feature can be updated to just detect tags in the `## Tags` section or even in both `## Tags` and `## Comment` to avoid this if it's still noisy. I left it a little more free-form to see how it goes.

@cainwatson The character for identifying tags could be  made into a customizable feature. There is a bit of tag-matching code and tests that would need updating so I'll have to work toward that.

**Comment by xwmx** [comment]
I was getting a lot of issue numbers showing up as tags so I went ahead and limited matching in bookmarks to tags in the `## Comment` and `## Tags` sections. Seems to work pretty well now.

**Comment by xwmx** [comment]
Version 6 is now available with this feature. Thanks for the suggestion!
